### ISSUE TITLE
Node gyp issues

### ISSUE THREAD

**Issue by Ironholds** [rstudio/shiny-server#108]
64-bit ubuntu, building from source, works fine until <code>(cd .. && ext/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js --python="$PYTHON" rebuild)</code> at which point we end up with errors ending like:

>/root/.node-gyp/0.12.0/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
../src/posix.cc:242:15: error: ‘NewSymbol’ is not a member of ‘v8::String’
   target->Set(String::NewSymbol("acquireRecordLock"),
               ^
../src/posix.cc:243:46: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
       FunctionTemplate::New(AcquireRecordLock)->GetFunction());
                                              ^
../src/posix.cc:243:46: note: candidate is:
In file included from /root/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/posix.cc:13:
/root/.node-gyp/0.12.0/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/root/.node-gyp/0.12.0/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
../src/posix.cc: In function ‘v8::Handle<v8::Value> GetPwNam(const int&)’:
../src/posix.cc:63:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/posix.cc: In function ‘v8::Handle<v8::Value> GetPwUid(const int&)’:
../src/posix.cc:103:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/posix.cc: In function ‘v8::Handle<v8::Value> GetGroupList(const int&)’:
../src/posix.cc:166:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/posix.cc: In function ‘v8::Handle<v8::Value> GetGrNam(const int&)’:
../src/posix.cc:198:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/posix.cc: In function ‘v8::Handle<v8::Value> AcquireRecordLock(const int&)’:
../src/posix.cc:231:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [Release/obj.target/posix/src/posix.o] Error 1
make: Leaving directory `/root/shiny-server/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/shiny-server/ext/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.13.0-43-generic
gyp ERR! command "node" "/root/shiny-server/ext/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "--python=" "rebuild"
gyp ERR! cwd /root/shiny-server
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok

**Comment by trestletech** [comment]
What version of Ubuntu are you using? And are you using the pre-build DEB files or building from source?

**Comment by Ironholds** [comment]
Ubuntu 14.04.2, and see the second clause of my first sentence, which is "building from source"

**Comment by trestletech** [comment]
Is there a reason you're not using the pre-compiled .deb files available from http://www.rstudio.com?

**Comment by Ironholds** [comment]
The precompiled debs are for amd 64-bit releases, not x86-based; for those, the advice is to build from source.

**Comment by aronatkins** [comment]
I have successfully built `shiny-server` on Ubuntu 14.04.1, but there is obviously a difference between our environments.

The build for @Ironholds is using `/root/.node-gyp/0.12.0` instead of `/root/.node-gyp/0.10.25`. The build is using `0.12.0` headers instead of `0.10.25`, which are incompatible.

From the `shiny-server` directory, could you try running the following before the `node-gyp` step:
```
./ext/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js --python="$PYTHON" install
```

I'm hopeful that the `install` step will install headers for `0.10.25` and avoid this issue.

If it doesn't, could you give us the output from:
```
./ext/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js list
```

I am hesitant to recommend removing versions other than `0.10.25`, but that can be accomplished with:
```
./ext/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js remove 0.12.0
```
It's a heavy approach, which is why I recommended the `install` as a first approach.

**Comment by Ironholds** [comment]
No luck. Darn :(. Output for list is:

>root@i2:~/shiny-server# ./ext/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js list
gyp info it worked if it ends with ok
gyp info using node-gyp@0.10.10
gyp info using node@0.12.0 | linux | x64
0.10.21
0.12.0
gyp info ok

**Comment by aronatkins** [comment]
Ok. Not sure yet why `node-gyp` is using the wrong version, but this should remove headers from those other versions:
```
./ext/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js remove 0.12.0
./ext/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js remove 0.10.21
```

If that feels too destructive, you could temporarily move `$HOME/.node-gyp` aside.

**Comment by Ironholds** [comment]
Well, that's weird. Removing it works, and then <code>(cd .. && ext/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js --python="$PYTHON" rebuild)</code> breaks. FWIW, that rebuild command is trying to use 12.0.

**Comment by aronatkins** [comment]
Ok. Let's try forcing the version of node and see if that helps:
```
./bin/node ./ext/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js --python="$PYTHON" rebuild
```

**Comment by aronatkins** [comment]
I think that's going to fix it; we add our version of node to the **end** of the path, meaning any system node resolves first.
```
DIR=`pwd`
PATH=$PATH:$DIR/../bin/
```
I think the right way to rewrite the path is:
```
DIR=`pwd`
PATH=$DIR/../bin:$PATH
```
But being explicit about the node path is also a fine solution.

**Comment by Ironholds** [comment]
Now installs, although the combination of ghost and shiny on the same machine seems to lead to conflicts when it comes to finding directories. Hrn. I'll iterate on it; thanks!

**Comment by aronatkins** [comment]
Thanks for the patience; I'll update our instructions to explicitly use our built-node.
