### ISSUE TITLE
"bad file descriptor" issue

### ISSUE THREAD

**Issue by Ironholds** [rstudio/shiny-server#117]
Running "make" after the preceding commands in the instructions for building from source generates:

>flock /home/ironholds/shiny-server/external/node/node-v0.10.21/out/Release/linker.lock g++ -pthread -rdynamic -m64  -o /home/ironholds/shiny-server/external/node/node-v0.10.21/out/Release/mksnapshot -Wl,--start-group /home/ironholds/shiny-server/external/node/node-v0.10.21/out/Release/obj.target/mksnapshot/deps/v8/src/mksnapshot.o /home/ironholds/shiny-server/external/node/node-v0.10.21/out/Release/obj.target/deps/v8/tools/gyp/libv8_base.a /home/ironholds/shiny-server/external/node/node-v0.10.21/out/Release/obj.target/deps/v8/tools/gyp/libv8_nosnapshot.a -Wl,--end-group 
flock: /home/ironholds/shiny-server/external/node/node-v0.10.21/out/Release/linker.lock: Bad file descriptor
make[4]: *** [/home/ironholds/shiny-server/external/node/node-v0.10.21/out/Release/mksnapshot] Error 65
make[3]: *** [node] Error 2
make[2]: *** [external/node/node-prefix/src/node-stamp/node-build] Error 2
make[1]: *** [external/node/CMakeFiles/node.dir/all] Error 2
make: *** [all] Error 2

Ubuntu 14.04, 64-bit, building from source.

**Comment by aronatkins** [comment]
I am unable to trigger the same failure following the instructions from: https://github.com/rstudio/shiny-server/wiki/Building-Shiny-Server-from-Source

I am using an Ubuntu Vagrant image from: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box

Anything more about your configuration that's interesting?

**Comment by Ironholds** [comment]
Not to my knowledge? I actually managed to get the .deb installer working in the end, so I'll just call it a weirdness in the circuits and mark it "closed" :). Will let people know if it happens again.
