### ISSUE TITLE
shiny-server to follow symbolic links?

### ISSUE THREAD

**Issue by mmuurr** [rstudio/shiny-server#119]
Is there any directive to permit shiny-server to follow symbolic links?
Example (desired) use case:
```
+---/myApp
    +---server.R
    +---ui.R
    +---www
        +---some_plugin.js -> ../lib/some_plugin_v1/the_plugin_code.js
    +---lib
        +---some_plugin_v1
            +---the_plugin_code.js
    +---lib
        +---some_plugin_v2
            +---the_plugin_code.js
```

In the current world, it appears the symlink under ```www``` isn't followed, so swapping between versions of the plugin require copying the file to the ```www``` location.

Tangentially related: it seems that server-level apps use ```assets``` as the subdirectory in which to find additional files, but for user-level apps it's ```www```... is this distinction intentional?
(It's easy enough to rename the directories when migrating user-level apps to server-level and vice-versa, but it's not documented in the current shiny-server configuration guide, so might be worth a documentation addition.)

**Comment by jcheng5** [comment]
It's actually not shiny-server that has this restriction, it's Shiny--do you mind filing an issue on the rstudio/shiny repo, please?

I don't think any user or app author should have to be concerned about `assets` directories--those are files that are essentially shiny-server implementation details. Is there somewhere you're finding you need to use `assets` directories?

**Comment by mmuurr** [comment]
I'll file the symlink request in rstudio/shiny, sure.

For the other point, I might've just been confused by the example in section 2.7.1 of the Shiny-Server Admin Guide. A second reading leads me to believe that I can name the `assets` directory in that example to whatever I choose, e.g. `www`, and refer to files living in that directory from my apps like so: `../www/my_img.jpg`.

(For some reason, I though the structure shown in the 2.7.1 example was hard-coded and `assets` was the required dirname for any shared files between apps. I'm easily confused :-)
