### ISSUE TITLE
Reproducible Install from Source Error

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny-server#140]
I list the reproducible steps, using a totally new virtual server such as from Digital Ocean. Can it be fixed soon ? The error is :

    [2015-08-05 21:11:53.445] [INFO] shiny-server - Shiny Server v1.4.0.0 (Node.js v0.10.21)
    [2015-08-05 21:11:53.448] [INFO] shiny-server - Using config file "/etc/shiny-server/shiny-server.conf"
    [2015-08-05 21:11:53.465] [ERROR] shiny-server - Error loading config: File "/etc/shiny-server/shiny-server.conf" does not exist
    [2015-08-05 21:11:53.465] [INFO] shiny-server - Shutting down worker processes

The steps are : 
1. Add deb to sources.list file
    deb http://cran.rstudio.com/bin/linux/ubuntu vivid/
2. get key
   apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
3. Install R
    sudo apt-get update
    sudo apt-get install r-base
    sudo apt-get install r-base-dev
4. Install Shiny.
   install.packages("shiny") # in R.
5. Install git.
   apt-get install git
6. Install cmake.
   apt-get install cmake
7. Copy instructions from Github website
git clone https://github.com/rstudio/shiny-server.git
cd shiny-server
mkdir tmp
cd tmp

DIR=`pwd`
PATH=$DIR/../bin:$PATH

PYTHON=`which python`
$PYTHON --version

cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DPYTHON="$PYTHON" ../
make
mkdir ../build

(cd .. && ./bin/npm --python="$PYTHON" rebuild)
(cd .. && ./bin/node ./ext/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js --python="$PYTHON" rebuild)

sudo make install

sudo ln -s /usr/local/shiny-server/bin/shiny-server /usr/bin/shiny-server
sudo useradd -r -m shiny

sudo mkdir -p /var/log/shiny-server
sudo mkdir -p /srv/shiny-server
sudo mkdir -p /var/lib/shiny-server
sudo chown shiny /var/log/shiny-server
sudo mkdir -p /etc/shiny-server

    # uname -a
    Linux TMP 3.19.0-22-generic #22-Ubuntu SMP Tue Jun 16 17:14:22 UTC 2015 i686 i686 i686 GNU/Linux

**Comment by trestletech** [comment]
You need to create a config file at that location. You could copy the file from `config/default.config` there. 

In general, the "supported" mechanism for installation is to use the .deb installers we provide [here](https://www.rstudio.com/products/shiny/shiny-server/).

**Comment by DarioS** [comment]
Could 32-bit versions be added to the website ? I notice that RStudio Server has both varieties available to download. The 32-bit variety should perform better on servers with small RAM, such as the virtual server which we use (1 GB RAM).

I copied the default configuration file, but it hangs at: 

    [2015-08-10 22:34:18.858] [INFO] shiny-server - Starting listener on 0.0.0.0:3838

Is there anything else I need to modify, if I proceed trying to install from source ?
