### ISSUE TITLE
An error has occurred  The application failed to start.  The application exited during initialization.

### ISSUE THREAD

**Issue by harryprince** [rstudio/shiny-server#153]
I fail to use shiny by some unknown reasons.
I have try lots of methods from google,gmail-groups and so on.

here is  my site: http://52.88.172.224:3838/sample-apps/hello/

```
uname -a
Linux 85e56e7be938 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.10

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base
```

and

```
> library(shiny)
```

successfully use shiny.

```
shiny-server
[2015-10-22 03:06:38.300] [INFO] shiny-server - Shiny Server v1.4.0.756 (Node.js v0.10.21)
[2015-10-22 03:06:38.302] [INFO] shiny-server - Using config file "/etc/shiny-server/shiny-server.conf"
[2015-10-22 03:06:38.332] [WARN] shiny-server - Running as root unnecessarily is a security risk! You could be running more securely as non-root.
[2015-10-22 03:06:38.334] [INFO] shiny-server - Starting listener on 0.0.0.0:3838
[2015-10-22 03:06:38.338] [ERROR] shiny-server - HTTP server error (0.0.0.0:3838): listen EADDRINUSE
[2015-10-22 03:06:38.338] [INFO] shiny-server - Shutting down worker processes
```

and I use the default conf

```
sudo /opt/shiny-server/bin/deploy-example default
```

I am still curiosity the problem, and I fail to use 

```
stop shiny-server 
restart shiny-server
```

there is no any response on terminal.

and I use this command to watch the thread

```
ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.4  28884  4660 ?        Ss   Oct17   0:00 /usr/bin/python3 -u /sbin/my_init
root         8  0.0  0.0    188    32 ?        S    Oct17   0:04 /usr/bin/runsvdir -P /etc/service
root         9  0.0  0.0    168     4 ?        Ss   Oct17   0:00 runsv syslog-forwarder
root        10  0.0  0.0    168     4 ?        Ss   Oct17   0:00 runsv syslog-ng
root        11  0.0  0.0    168     4 ?        Ss   Oct17   0:00 runsv cron
root        14  0.0  0.0  28872   356 ?        S    Oct17   0:00 /usr/sbin/cron -f
root        15  0.0  0.2  64044  2580 ?        S    Oct17   0:00 syslog-ng -F -p /var/run/syslog-ng.pid --no-caps
root        16  0.0  0.0   7232   188 ?        S    Oct17   0:19 tail -F -n 0 /var/log/syslog
root        42  0.0  0.0  18260   552 ?        Ss+  Oct17   0:00 /bin/bash
root       472  0.0  0.0  18148   460 ?        Ss+  Oct17   0:00 /bin/bash
root       633  0.0  0.0  18152   616 ?        Ss+  Oct17   0:00 /bin/bash
root      2485  0.0  0.2  18168  2048 ?        Ss   02:24   0:00 /bin/bash
root      2510  0.0  0.0    168     4 ?        Ss   02:27   0:00 runsv shiny-server
root      2511  0.0  3.9 977952 39924 ?        Sl   02:27   0:00 /opt/shiny-server/ext/node/bin/shiny-server /opt/shiny-
root      2581  0.0  0.1  48360  1840 ?        S    02:49   0:00 sudo su
root      2582  0.0  0.1  48992  1520 ?        S    02:49   0:00 su
root      2583  0.0  0.2  21036  2092 ?        S    02:49   0:00 bash
root      2737  0.0  0.1  18444  1296 ?        R+   03:08   0:00 ps -aux
```

even I attempt to kill some related thread, these pid will be restart automaticlly

```
kill 2510 2511
```

the problem still here

```
ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.4  28884  4660 ?        Ss   Oct17   0:00 /usr/bin/python3 -u /sbin/my_init
root         8  0.0  0.0    188    32 ?        S    Oct17   0:04 /usr/bin/runsvdir -P /etc/service
root         9  0.0  0.0    168     4 ?        Ss   Oct17   0:00 runsv syslog-forwarder
root        10  0.0  0.0    168     4 ?        Ss   Oct17   0:00 runsv syslog-ng
root        11  0.0  0.0    168     4 ?        Ss   Oct17   0:00 runsv cron
root        14  0.0  0.0  28872   356 ?        S    Oct17   0:00 /usr/sbin/cron -f
root        15  0.0  0.2  64044  2580 ?        S    Oct17   0:00 syslog-ng -F -p /var/run/syslog-ng.pid --no-caps
root        16  0.0  0.0   7232   188 ?        S    Oct17   0:19 tail -F -n 0 /var/log/syslog
root        42  0.0  0.0  18260   552 ?        Ss+  Oct17   0:00 /bin/bash
root       472  0.0  0.0  18148   460 ?        Ss+  Oct17   0:00 /bin/bash
root       633  0.0  0.0  18152   616 ?        Ss+  Oct17   0:00 /bin/bash
root      2485  0.0  0.2  18168  2048 ?        Ss   02:24   0:00 /bin/bash
root      2581  0.0  0.1  48360  1840 ?        S    02:49   0:00 sudo su
root      2582  0.0  0.1  48992  1520 ?        S    02:49   0:00 su
root      2583  0.0  0.2  21040  2096 ?        S    02:49   0:00 bash
root      2738  0.0  0.0    168     4 ?        Ss   03:10   0:00 runsv shiny-server
root      2739 24.0  3.6 704840 36912 ?        Sl   03:10   0:00 /opt/shiny-server/ext/node/bin/shiny-server /opt/shiny-
root      2745  0.0  0.1  18444  1296 ?        R+   03:10   0:00 ps -aux
```

I need help, thanks!

**Comment by fereshtehRS** [comment]
The error you are receiving the shiny-server log indicates that the port (3838) is in use. You can run a command like the following to check that:

```
netstat --tcp -a -n -p | grep 3838
```

And you can configure your Shiny Server to run on a different port that is not being used. (e.g 3839)

**Comment by jcheng5** [comment]
Look at `/var/log/shiny-server/*.log` on the server to see if you can find the error log for your app.

BTW, are you running in a docker container or something?

**Comment by Erko85** [comment]
Hi,

I am experiencing the same problem. Any solution in sight?

**Comment by Erko85** [comment]
ok my problem wasn't with Rshiny but with the internal ufw
In order to fix it I did 
sudo ufw allow 3838/tcp

Then it worked on ubuntu 14.04 on aws

**Comment by kmezhoud** [comment]
Hi,
It looks like you do not have right permission to access ```/srv/shiny-server```.
try to change in ``` /etc/shiny-server/shiny-server.conf ```  
```run_as shiny``` by ```run_as session_name``` 
or maybe
```
cd /srv/shiny-server
chmod 555 shiny-app
```

**Comment by ErrolK** [comment]
Hi,

I did have access. The main problem was that the firewall wasn't open.

Thanks for taking the time to answer

**Comment by agarwalnaimish** [comment]
I did the following to get it running:

1.  `sudo gedit /etc/shiny-server/shiny-server.conf` and then changed `run_as shiny` to `run_as username` which in my case is `run_as agarwalnaimish`.
2. `sudo ufw allow 3838/tcp`

**Comment by harryprince** [comment]
`ln -s <your_lib> <sys_lib>` can sovle this problem.

and  `ls  -lrt /var/log/shiny-server/*.log |tail -1`
can get latest shiny-server app log instantly.

**Comment by paullintilhac** [comment]
I am having the same issue. However, I don't want to run `sudo ufw allow 3838/tcp` because I am using apache as a gateway for authentication, according to this: https://www.r-bloggers.com/password-protect-shiny-apps/. Does this mean that my reverse proxy isn't congifured correctly?

**Comment by fereshtehRS** [comment]
@paullintilhac Can you please provide the following info:

- The apache reverse proxy configuration 
- Shiny server configuration file (/etc/shiny-server/shiny-server.conf)
- The error messages from /var/log/shiny-server.log file
- Any error in the application log file: /var/log/shiny-server/<appname>-xxxx.log

**Comment by cc886** [comment]
I found out my problem was that I didn't install the shiny package.

`sudo su - \
-c "R -e \"install.packages('shiny', repos='https://cran.rstudio.com/')\""`

REF: https://www.rstudio.com/products/shiny/download-server/

**Comment by XiaoruiZhu** [comment]
I spent a lot of time reading through you guys solution but still not work, until I find it could be the problem of "Configuring Firewall" of your instance. 

If you deploy your instance in AWS or Aliyun, go to **"Security Group" and add a rule for 3838(whatever port you set in your shiny-server.conf).** Then you will have the permission to access shiny-server.

**Comment by jmzeng1314** [comment]
I also got this problem, but that's my fault. 
I use the `sudo chgrp -R shiny-apps  /srv/shiny-server/`  as some other tutorial. 
So I should change it back, `sudo chgrp -R shiny  /srv/shiny-server/`

By the way, be careful about the files 

1. Shiny server configuration file (/etc/shiny-server/shiny-server.conf)
2. The error messages from /var/log/shiny-server.log file
3. Any error in the application log file: /var/log/shiny-server/-xxxx.log

**Comment by ray1919** [comment]
In my case, some package was installed in user dir, and the server was run_as shiny, so it could not find some package like "digest", this caused the error.

the solution is as what @agarwalnaimish answered.

**Comment by Harish2f** [comment]
> Hi,
> It looks like you do not have right permission to access `/srv/shiny-server`.
> type `shiny-server`to see if you have access.
> If not try to change in `/etc/shiny-server/shiny-server.conf`
> `run_as shiny` by `run_as session_name`
> `sudo restart shiny-server`
> or maybe
> 
> ```
> cd /srv/shiny-server
> chmod 555 shiny-app
> sudo restart shiny-server
> ```

Hi I dont have the access to right or access the shiny server. What should I do about it?

**Comment by zyt33333** [comment]
Why is the URL created an invalid URL。demonstrate：The application failed to start.
