### ISSUE TITLE
Not installable on Ubuntu 15.10 (Wily Werewolf)

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shiny-server#156]
```
vagrant@vagrant-ubuntu-wily-64:~$ sudo gdebi shiny-server-1.4.1.762-amd64.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: libssl0.9.8
```

@jjallaire Do you remember why we have a libssl0.9.8 dependency and not libssl1.0.0? I feel like you had a better handle on this than I did.

**Comment by jjallaire** [comment]
It was due to building on Redhat5 / Ubuntu 10.04. If you guys now build on
more recent versions there's no need for libssl0.9.8.

**Comment by jcheng5** [comment]
@jjallaire Do I just remove the libssl0.9.8 dependency altogether, or do I replace it with libssl1.0.0? Just remove it, right?

**Comment by jcheng5** [comment]
In case anyone needs a workaround for now:

```r
sudo dpkg -i --force-depends shiny-server-commercial-1.4.1.657-amd64.deb
```

**Comment by jjallaire** [comment]
Yes, you can remove the libssl0.9.8 dependency entirely for any package
built on RHEL >= 6 or Ubuntu >= 12.04.

**Comment by byorl-art** [comment]
@jcheng5 the workaround works but can't install further packages using apt. I have to uninstall shiny-server then install packages and then install shiny-server again.

**Comment by bradhowes** [comment]
@byorl-art You can play with fire and remove the dependency in /var/lib/dpkg/status. Edit the file as root, search for 'shiny-server' and remove the 'Depends:' line (only has libssl IIRC). Validate that all is good with a 'apt-get -f install' -- you should not see 'shiny-server' listed as a package to be removed.

**Comment by zhilongjia** [comment]
Inspired by @bradhowes, user can edit the package directly.

    mkdir tmp
    dpkg-deb -R shiny-server-1.4.1.759-amd64.deb tmp
    vim tmp/DEBIAN/control and change 0.9.8 into 1.0.0.
    dpkg-deb -b tmp shiny-server-1.4.1.759.1-amd64.deb
    dpkg -i shiny-server-1.4.1.759.1-amd64.deb

ref: http://unix.stackexchange.com/questions/138188/easily-unpack-deb-edit-postinst-and-repack-deb

**Comment by nikolai-b** [comment]
It would be very useful if you could set this as libssl0.9.8 or higher.
There are lots of know vulnerabilities to 0.9.8 and some are [severe](https://www.cvedetails.com/vulnerability-list.php?vendor_id=217&product_id=383&version_id=26306&page=1&hasexp=0&opdos=0&opec=0&opov=0&opcsrf=0&opgpriv=0&opsqli=0&opxss=0&opdirt=0&opmemc=0&ophttprs=0&opbyp=0&opfileinc=0&opginf=0&cvssscoremin=9&cvssscoremax=0&year=0&month=0&cweid=0&order=1&trc=50&sha=8f90c0f7e6cd31339b99ff0a5ac50b282f6b13ec)

**Comment by nikolai-b** [comment]
Any news?

**Comment by fereshtehRS** [comment]
@nikolai-b That build has the fix for the issue as you have found out. Sorry this ticket wasn't updated.
