### ISSUE TITLE
Shiny app stop working after a while

### ISSUE THREAD

**Issue by zippeurfou** [rstudio/shiny-server#169]
Hi,
I did install shiny on AWS linux image. Everything was working great. However, after a while I can't access my app.
It seems to have to do with linux and tmp folder that might autodelete things...

here is what I see on the screen:
```
path[1]="/tmp/RtmpQRzSFD/filed43db08a4e_files/jquery-1.11.0": No such file or directory
```
Here is what the console tell me (edited the dns here):
```
(program):4070 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
(program):4070 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.
http://xx.com/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
sockjs-0.3.min.js:27 WebSocket connection to 'ws://xx.com/topic_performance/__sockjs__/846/cbz_qo_2/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
shiny-server.js:238 Fri Dec 11 2015 10:11:44 GMT-0500 (Est): Connection opened. http://xx.com/topic_performance/
```

When I look into my tmp folder. This directory does not exist.

How do I make shiny not write in tmp or my linux not delete tmp files or just shiny server work...

Ok, after looking at the log:

the log file:

```
/tmp/RtmpUGlhrG/filedcc87ae3d1.html: hClose: resource exhausted (No space left on device)
```

It appears I have no more space on my image. My bad

**Comment by msummersgill** [comment]
@zippeurfou Having an issue with symptoms very similar to what you described, did you happen to figure out a resolution on this issue?

In our case the /tmp directory is getting filled up with numerous copies of various javascript libraries used to render shiny and markdown elements that are not being deleted after the session is closed.
