### ISSUE TITLE
RODBC Connection Brings Down Shiny Server

### ISSUE THREAD

**Issue by wordsofcasey** [rstudio/shiny-server#173]
We've been struggling with this nasty issue for a while, and I'm pretty certain it's a bug in the server.

**Environment**:
* OS - RedHat 6.7
* Shiny Version - 0.12.2

**Summary**:
If there is an RODBC connection in the Shiny Server code, then a segfault will be generated.

**Reproducer**:
1. Create a shiny app and add an RODBC connection that queries a database.
2. View the app and you should get a traceback.

There are more details as well as a stack trace in the following links.

http://stackoverflow.com/questions/34316243/rodbc-query-brings-down-shiny-server
https://groups.google.com/forum/#!topic/shiny-discuss/66Ve60ugmHs

**Comment by fereshtehRS** [comment]
What is the version of Shiny Server? (assuming it is the Shiny Server process that crashes, right?)

**Comment by wordsofcasey** [comment]
Version 1.4.1.759. Yes, it's the process that crashes.

shiny-server-1.4.1.759-rh5-x86_64.rpm

**Comment by wordsofcasey** [comment]
I've resolved the issue.

**Links to resolution**

* http://stackoverflow.com/questions/34316243/rodbc-query-brings-down-shiny-server
* https://groups.google.com/forum/#!topic/shiny-discuss/66Ve60ugmHs
