### ISSUE TITLE
using shinyAppDir() does not seem to recognize global.R

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny-server#180]
I'm using shiny server pro (if you need the version number, then please remind me how to find out?) and I've noticed that when I try to run apps in a different directory with shinyAppDir() , objects defined in global.R are not recognized.

**Example:**

test1/global.R:

```
myvar <- 10
```

test1/ui.R:

```
fluidPage("HELLO", myvar)
```

test1/server.R:

```
server <- function(input, output, session) {
  cat(myvar)
}
````

If I go to the URL for this app, it works.

But if I have in a different directory

test2/app.R:
```
setwd("../test1")
shiny::shinyAppDir(".")
```

And go to that app directory, I get error `ERROR: object 'myvar' not found.` If I add a `source("global.R")`, then it works.

Repeating this on my local computer does not result in an error.

**Comment by jcheng5** [comment]
Discussion [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/shiny-discuss/ibAXs3zLWAs/YOVRVRU2AQAJ)

**Comment by jcheng5** [comment]
Actually let's use the Shiny bug, it's not an SS/SSP problem

**Comment by daattali** [comment]
I think I placed it here because running this code on my personal laptop did work, but in shiny server it did not
