### ISSUE TITLE
Wiki: Build from source page has not-working link to init scripts

### ISSUE THREAD

**Issue by thomasteoh** [rstudio/shiny-server#191]
Not working: https://github.com/rstudio/shiny-server/tree/binaries/config/init.d

Should it be this one?: https://github.com/rstudio/shiny-server/tree/master/config/init.d

**Comment by fereshtehRS** [comment]
Broken link on this page:
https://github.com/rstudio/shiny-server/wiki/Building-Shiny-Server-from-Source

Search for:
```
We provide some init.d scripts here that may serve as a useful guide for you
```

**Comment by trestletech** [comment]
It definitely should be! Thanks, @thomasteoh
