### ISSUE TITLE
Multiplex wrapper

### ISSUE THREAD

**Issue by detule** [rstudio/shiny-server#192]
Hi team,

I posted <a href='https://github.com/rstudio/shiny-server/commit/a0e558d40a4dde792bb29ba795b993768267657b#commitcomment-15521010'>this</a> comment a few weeks ago.  Not sure if it slipped through the cracks, or if I am completely off-base here (in thinking that `readyState` is not directly accessible for robust connections).

Thanks again for your hard work.

**Comment by jcheng5** [comment]
Are you depending on the readyState for something in your own app? (I'm in the middle of refactoring this whole file so your input would be appreciated)

**Comment by detule** [comment]
Joe,
Thanks for the quick response.
No dependency on my end.  Given the scope of the recent changes, I was doing some extended testing before merging them locally.  This failure:

`this.$conn.readyState === 1` consistently evaluating as false, as `typeof(this.$conn.readyState)==='undefined'` 

cropped up through the testing process, and I thought I would give you a heads up.

Cheers.
