### ISSUE TITLE
disconnect from server shiny without any error, works locally fine

### ISSUE THREAD

**Issue by nephantes** [rstudio/shiny-server#201]
I deployed it here;
https://nephantes.shinyapps.io/debrowser/
It doesn't give any error when it disconnects. Last logs are below;
It is working totally fine locally. But on shiny server. It just disconnects suddenly. There is only one user and memory usage is less than 100MB on 1G machine.
How can I look at more detailed logs about the crash. It crashes a way before the time limit. Let me know how I can solve it? Thanks!

rsconnect::showLogs()
...
2016-04-04T22:58:30.462754+00:00 shinyapps[90516]: RECV {"method":"update","data":{"startQCPlot:shiny.action":1}}
2016-04-04T22:58:30.464829+00:00 shinyapps[90516]: SEND {"progress":{"type":"binding","message":{"id":"qcplotout"}}}
2016-04-04T22:58:30.466002+00:00 shinyapps[90516]: SEND {"custom":{"busy":"busy"}}
2016-04-04T22:58:30.468567+00:00 shinyapps[90516]: SEND {"custom":{"recalculating":{"name":"qcplotout","status":"recalculating"}}}

**Comment by bborgesr** [comment]
Hmmm, try it again, maybe? I could access it jut fine (it does take some time to compute things, but it is functional...) Does it crash immediately for you?

**Comment by nephantes** [comment]
Not immediately, when you try draw heatmap while alldata is selected. It is using more cpu and memory for sure but it is less than 1G. I also want to see the reason of it. I have this problem only deployed versions. On local rstudio, it never disconnects.

**Comment by zhilongjia** [comment]
When I click the _plot_ tab, [D2Dpage](https://zhilong.shinyapps.io/D2Dpage/) has the same problem, "Disconnected from the server" in shinyapps but not in local shiny server. Probably related with the resources. Thank you.

**Comment by fereshtehRS** [comment]
@zhilongjia Can you please post your issue to https://groups.google.com/forum/#!forum/shinyapps-users so shinyapps.io developers can look at your app and server logs to find the root cause. But as you mentioned this could be related to resources. The first thing you might want to try is to increase the container size (more memory).

@nephantes I saw that you had posted your issue on https://groups.google.com/forum/#!forum/shinyapps-users  If you are still seeing the issue, please respond to that posting.

**Comment by nephantes** [comment]
Solved. When I use nginx rather than apache server, disconnection issue solved.

**Comment by zhilongjia** [comment]
It does not solve my [D2Dpage](https://zhilong.shinyapps.io/D2Dpage/). Should it be deployed?
