### ISSUE TITLE
Admin Console behind reverse proxy path doesn't kill processes

### ISSUE THREAD

**Issue by chrisirhc** [rstudio/shiny-server#209]
Kill button doesn't work when using the Admin console behind a reverse proxy under a path.

We're reverse proxying to the admin console so that `http://shiny-host/admin/` goes to the admin console. However, the kill button is using the root of the host (`http://shiny-host/process/kill/<processId>`) and hitting a 404.

![image](https://cloud.githubusercontent.com/assets/132584/15226171/746f9dde-1836-11e6-96fe-9649f1911cb0.png)

(On shiny-server 1.4.0.654)

**Comment by jcheng5** [comment]
(Resolved offline; proxying the `/process` path seemed to fix this)
