### ISSUE TITLE
no shiny-server.log

### ISSUE THREAD

**Issue by kforner** [rstudio/shiny-server#212]
Hello,

Running shiny server 1.4.1.784, in a docker container, with log_dir /var/log/shiny-server:
there is NO shiny-server.log in /var/log, nor in /var/log/shiny-server/.

**Comment by kforner** [comment]
ok, it seems that the log is output on stdout/stderr (undocumented), maybe because it detects that it is run in interactive mode. 

Shouldn't it be documented ? 

Thanks.

**Comment by trestletech** [comment]
We typically intend for Shiny Server to be run using an init system as we setup in the installer. In those modes the appropriate log files should be created. 

Running the binary itself manually will result in a number of known issues and deviations from our documentation.

It doesn't change the behavior when in interactive mode, but in our installer and init systems we redirect our logs to the above-mentioned log file. If you run the binary manually, you're likely not doing that.

Can you explain a bit more about your use case and why you aren't using the installer/init systems?

**Comment by kforner** [comment]
I use it in a docker, that's why I can not easily use the standard init systems.
Instead I just run the shiny-server exec, and I was surprised not to find the log file.
