### ISSUE TITLE
Need a tag or a tarball of the lastest release 1.4.4

### ISSUE THREAD

**Issue by heroxbd** [rstudio/shiny-server#224]
The build system download an outdated version of node.js 4.1.1, which is no longer supported upstream without any further security updates.

I have noje.js 6.2.2 installed on my system and want to use it with shiny-server.  It is nice to have an option of the build system to do so.

**Comment by jcheng5** [comment]
It shouldn't have downloaded any version of node v4, but Node v0.10.46, which is maintenance mode until October of this year. 

Unfortunately it's a lot of work to bring shiny server to a newer version of Node, as there were an enormous number of breaking changes between 0.10 and 0.12, but we are currently doing the work to get up to date (but probably v4 for stability--v4 is the current stable and will receive updates for years to come).

If you are sure it's running 4.1.1, let me know--that's very unexpected.

**Comment by heroxbd** [comment]
Hi jcheng5,

Thank you for your timely reply!

I am using v1.5-pre-rebase, it is downloading node.js 4.1.1. 

What is the latest official release?  joe/refactor/client-premerge does not look like a good name.

**Comment by jcheng5** [comment]
The latest official release is whatever is available for download on rstudio.com, the official "unstable" is whatever is on the master branch. All other branches should be considered scratch areas for individual developers (we had slightly higher ambitions for v1.5 branch but it didn't work out).

**Comment by heroxbd** [comment]
Hi, please correct me if I missed something

On rstudio.com,

  https://www.rstudio.com/products/shiny/download-server/

It pointed me to

  https://github.com/rstudio/shiny-server/wiki/Building-Shiny-Server-from-Source

Therefore I looked for  the releases section of the git repo, which gives " on Mar 8
joe/refactor/client-premerge" and " on Oct 1, 2015 v1.5-pre-rebase ".  Which one should I use to build shiny-server from source?  Or is there another official tarball available elsewhere?

**Comment by heroxbd** [comment]
FYI, the build log is at

  http://paste.debian.net/782192

**Comment by heroxbd** [comment]
Okay, after Cheng's hint, I realized 1.5-pre-rebase is not an official release.  It is related to #149.

The latest release is 1.4.4  according to NEWS,

> shiny-server 1.4.4
> --------------------------------------------------------------------------------
> 
> * Upgrade to Node.js v0.10.46 (security patches).

However, there is neither a git tag nor a tarball for shiny-server version 1.4.4.

**Comment by jcheng5** [comment]
Oh, sorry. We don't use git tags to denote releases, and even if we did the change to node 0.10.46 just went in a day or two ago and hasn't been released. You should simply download from master if you want that release. 

Is there a reason you're not using one of our installable binaries? Are you not on Debian/Ubuntu or CentOS/RedHat?

**Comment by heroxbd** [comment]
I am using shiny-server on a cluster node, where I don't have root permission.  The use case is related to #211.

At the same time, I am interest to package shiny-server for Gentoo, which has a complete CRAN and BIOC repository now[1].

1. https://wiki.gentoo.org/wiki/Project:Science/Overlay#Scientific_overlays

**Comment by hartzell** [comment]
I'm also interested in installing shiny-server in an alternate location, without root permission (also an HPC setting).

It would be very useful to be able to check out the sources corresponding to the various releases.

What is your motivation for not tagging them?

I see two commits that claim to bump the version number to 1.4.4

    5be3994d28b4dfaa626ae76faac008ba88d2203d
    6d68f9b4fdb5ecd3afb517a6f41b203c5de0644e

If I wanted source that corresponded to the 1.4.4 release, which commit (if either...) would I use?

**Comment by jcheng5** [comment]
> What is your motivation for not tagging them?

It's just that our build system doesn't work that way; the build numbers don't even get assigned until our CI server runs on Jenkins, and deciding which builds actually get released is a largely manual process that's downstream of that.

I'm releasing a version today, and I'll tag the build manually. I don't want to promise to always tag builds, but if you need to, you can extract the GIT_VERSION file from any .deb or .rpm, and if you look at the last segment of that string, and remove the "g" prefix, that'll tell you the commit hash. For example, `v1.4.0-198-gb07dcb7` means `b07dcb7`.

**Comment by hartzell** [comment]
Is there some alternative way that you could make tarballs of the release available?

**Comment by jcheng5** [comment]
I'll investigate having Jenkins at least push version tags back to GitHub.

**Comment by hartzell** [comment]
@jcheng5 -- Have you had any luck with figuring out a way to help us "source builders" figure out what commit corresponds to the latest release?

My first choice is still for you to actually "make a release" on github.  I know of folks making effective use of the `github-release` tool ([github repo here](https://github.com/aktau/github-release)); you could practically carve a jenkins job out of their example and put it downstream of the tail of your chain of release/build Jenkins jobs.

If you can't make the release on github or even tag the appropriate commit, perhaps you can include the commit hash in the metadata you're already including on the release page.  I could live with fishing it out by hand every once in a while and updating my builds.  Here's what I see currently:

```
64bit
Size:  60.6 MB
MD5: 2423ef792ee5b2aca5fbcf47cd958770
Version:  1.5.1.834
Released:  2016-11-04
```

Add

```
Commit: a6adccd
```

and I'd have something to hang my reputation on.

Thanks for your help!

**Comment by hartzell** [comment]
@jcheng5 -- Any info on tagging the releases?

**Comment by jcheng5** [comment]
OK, I've tagged the 1.5.* releases and I've put a solution in place going forward that should ensure that all future releases of shiny server (that are released to the rstudio.com website) get tagged as well. Thanks for your patience.

**Comment by heroxbd** [comment]
Thank you very much for your work, Cheng!

**Comment by hartzell** [comment]
**Thank you**!
