### ISSUE TITLE
Cannot start shiny-server

### ISSUE THREAD

**Issue by arcaneaura** [rstudio/shiny-server#225]
After running for 3 weeks, it suddenly stopped this morning. I tried to start with command "start shiny-server" but got this message "start: Job failed to start"

inside /var/log/shiny-server.log I found
/bin/sh: line 0: exec: shiny-server: not found

Can anyone help me with this?

**Comment by jcheng5** [comment]
@arcaneaura Did you figure this out? What does `which shiny-server` give you?

**Comment by arcaneaura** [comment]
@jcheng5 Yeah, I figure it out. Our server got hacked, the data are encrypted. It's not about shiny-server. Thanks for asking.
