### ISSUE TITLE
Problem with debian startup script

### ISSUE THREAD

**Issue by maillot-jaune** [rstudio/shiny-server#23]
Debian init script

I try to start shiny-server via [this](https://github.com/rstudio/shiny-server/blob/a08fafb9f41ae0e632651b0ca524ea5fba03f8f7/config/init.d/debian/shiny-server) but it's completely silent. 

 ~# cp shiny-server /etc/init.d
 ~# chmod +x /etc/init.d/shiny-server
 ~# update-rc.d shiny-server defaults
 ~# /etc/init.d/shiny-server start

But it's completely silent. Even when I do:

 ~# /etc/init.d/shiny-server foo

I get nothing...

I've installed shiny-server like so:
 ~# npm install -g shiny-server

Other info that might be useful:

R> packageVersion("shiny")
[1] ‘0.6.0’

R> version$version.string
[1] "R version 3.0.1 (2013-05-16)"

 ~# uname -a
Linux tatooine 2.6.32-5-amd64 #1 SMP Sun Sep 23 10:07:46 UTC 2012 x86_64 GNU/Linux

 ~# npm --version
1.2.14

 ~# node --version
v0.8.22

From the command line shiny-server starts fine...

 ~# shiny-server
[2013-06-28 12:15:34.118] [INFO] shiny-server - Shiny Server v0.3.5 (Node.js v0.8.22)
[2013-06-28 12:15:34.119] [INFO] shiny-server - Using config file "/usr/local/lib/node_modules/shiny-server/config/default.config"
[2013-06-28 12:15:34.133] [INFO] shiny-server - Starting listener on 0.0.0.0:3838

**Comment by hydrosIII** [comment]
Init Script still not working in Debian Jessie with sisvinit. I Had to change the DAEMON from shiny-server to /usr/bin/shiny-server as mdagost said. Can you reopen the bug and make this change, please it is juts one line of code.
