### ISSUE TITLE
Need to create /var/lib/shiny-server on install, or when creating bookmark dirs

### ISSUE THREAD

**Issue by wch** [rstudio/shiny-server#231]
The default bookmark dir is /var/lib/shiny-server/bookmarks. The current code will try to create that directory, but the parent, /var/lib/shiny-server/, doesn't exist, so it fails.

@jcheng5, do you think it's better to create that directory on install, or at runtime? The one drawback to creating it at runtime is that, because the dir is configurable, we might have to create an arbitrary number of parent directories first.

There does exist the [mkdirp](https://github.com/substack/node-mkdirp) module, but I don't know if it's worth bringing in another dependency for it.

**Comment by jcheng5** [comment]
In the past we have done stuff like this at install time.
