### ISSUE TITLE
Disabled Bookmarking Ignored by Server

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny-server#240]
In my global.R file I have

    enableBookmarking("disable") # Temporary workaround for bookmarks in non-writable system directory.

However, when I start an application by going to its public URL in an internet browser, I get the error

    [2016-09-15 14:43:55.136] [ERROR] shiny-server - Bookmark state directory creation failed: /var/lib/shiny-server/bookmarks

The server shouldn't be trying to create a bookmark directory for an application which isn't using them and in a folder I have no write access to.

Is this problem in Shiny or Shiny Server @wch ? I guessed the server, so I listed it here.

**Comment by wch** [comment]
Can you file this issue in the Shiny Server repo?

**Comment by wch** [comment]
Oh sorry, I previously thought this issue was in the Shiny repo, not Shiny Server.

**Comment by wch** [comment]
On app startup, the server will try to make sure that the top-level bookmarking directory (/var/lib/shiny-server/bookmarks) is there, even if the particular app doesn't have bookmarking enabled. When you actually bookmark an app, it will create some subdirectories underneath that top-level directory.

**Comment by wch** [comment]
Closing because the main issue is #239.
