### ISSUE TITLE
shiny-server doesn't compile on gentoo (solved)

### ISSUE THREAD

**Issue by fvalenduc** [rstudio/shiny-server#252]
I am trying to build shiny-server on gentoo, but unfortunately, compilation ends with this error:

Traceback (most recent call last):
  File "../../tools/gen-postmortem-metadata.py", line 520, in <module>
    emit_config();
  File "../../tools/gen-postmortem-metadata.py", line 473, in emit_config
    out = file(sys.argv[1], 'w');
NameError: name 'file' is not defined
deps/v8/tools/gyp/postmortem-metadata.target.mk:13 : la recette pour la cible « /usr/src/shiny-server/external/node/node-v0.10.47/out/Release/obj/gen/debug-support.cc » a échouée
make[4]: **\* [/usr/src/shiny-server/external/node/node-v0.10.47/out/Release/obj/gen/debug-support.cc] Erreur 1
make[4]: **\* Attente des tâches non terminées....
Makefile:43 : la recette pour la cible « node » a échouée
make[3]: **\* [node] Erreur 2
external/node/CMakeFiles/node.dir/build.make:113 : la recette pour la cible « external/node/node-prefix/src/node-stamp/node-build » a échouée
make[2]: **\* [external/node/node-prefix/src/node-stamp/node-build] Erreur 2
CMakeFiles/Makefile2:140 : la recette pour la cible « external/node/CMakeFiles/node.dir/all » a échouée
make[1]: **\* [external/node/CMakeFiles/node.dir/all] Erreur 2
Makefile:149 : la recette pour la cible « all » a échouée
make: **\* [all] Erreur 2
zsh: exit 2     make -j1

Does somebody have any idea about this problem ?
Thanks for your help.

**Comment by fvalenduc** [comment]
After googling a bit, I changed the code in node-v0.10.47/deps/v8/tools/gen-postmortem-metadata.py
 like this:

def emit_config():
        out = open(sys.argv[1], 'w');

        out.write(header);

        out.write('/* miscellaneous constants */\n');
        emit_set(out, consts_misc);

        out.write('/* class type information */\n');
        consts = [];
        keys = list(typeclasses.keys());
        keys.sort();
        for typename in keys:
                klass = typeclasses[typename];
                consts.append({
                    'name': 'type_%s__%s' % (klass, typename),
                    'value': typename
                });

        emit_set(out, consts);

        out.write('/* class hierarchy information */\n');
        consts = [];
        keys = list(klasses.keys());
        keys.sort();
        for klassname in keys:
                pklass = klasses[klassname]['parent'];
                if (pklass == None):
                        continue;

                consts.append({
                    'name': 'parent_%s__%s' % (klassname, pklass),
                    'value': 0
                });

        emit_set(out, consts);

        out.write('/* field information */\n');
        emit_set(out, fields);

        out.write(footer);

So, a file call is replaced by open and  keys = typeclasses.keys() is replaced by  keys = list(typeclasses.keys()) (and similarly for  keys = list(klasses.keys()). This solves the compile error and it works.

See also https://bugs.launchpad.net/raise/+bug/1217513 and http://stackoverflow.com/questions/16736833/python-nameerror-name-file-is-not-defined

**Comment by jcheng5** [comment]
Thanks! We've replaced Node v0.10 with Node v6--I don't know if it will compile on Gentoo out of the box now, if you encounter any other issues with newer builds please feel free to reopen this issue or file another one.
