### ISSUE TITLE
index.Rmd not being served by default?

### ISSUE THREAD

**Issue by alchenist** [rstudio/shiny-server#256]
Documentation reads 'If a request is made to a directory rather than to a particular Rmd file, Shiny Server will attempt to serve the file index.Rmd. If that file does not exist, the user will get an error alerting them that the file is not available.'

I have the following structure within a `/home/user/ShinyApps/app/` directory: 
```
├── bar.Rmd
├── baz.Rmd
├── foo.Rmd
├── index.Rmd
```

There are no other Shiny apps or an index.html in the directory, yet when I attempt to access http://server/user/app/, I get a 404.

**Comment by fereshtehRS** [comment]
- What version of Shiny Server are you running? (you can run `shiny-server --version` command)
- Please send us the configuration file (`/etc/shiny-server/shiny-server.conf` file)
- Also try the following:

`cp -r /opt/shiny-server/samples/sample-apps/rmd/  /home/user/ShinyApps`   (adjust the path)

and then access `http://server/user/rmd/`

**Comment by alchenist** [comment]
I reloaded Shiny Server and the issue disappeared. Thanks for the help.

For reference, Shiny Server v.1.4.2.786 and node v0.10.40. Conf file copied below. 

```
run_as :HOME_USER:;
server {
  listen 3838;

  location / {
    user_dirs;
    
    app_init_timeout 600;
    app_idle_timeout 600;
    
    directory_index on;
    
    members_of shiny;
  }
}
```

**Comment by fereshtehRS** [comment]
Good to hear that. Thanks for the update.
