### ISSUE TITLE
Please tag latest release

### ISSUE THREAD

**Issue by tillea** [rstudio/shiny-server#280]
Hi,
I consider packaging shiny-server for Debian.  When checking the release tags the latest one points to version 1.5.0.831 while a doc provides downloads of binaries for version 1.5.3.838.  It would be great if the tags for the source versions would be in sync with the binaries.
Kind regards, Andreas.

**Comment by hartzell** [comment]
See also #224

**Comment by jcheng5** [comment]
They should be tagged now and they'll be in sync going forward. Thanks.

**Comment by hartzell** [comment]
**Thank you!**
