### ISSUE TITLE
ggplot and random number generation with Shiny

### ISSUE THREAD

**Issue by ProgramErgoSum** [rstudio/shiny-server#281]
I have a Monte-Carlo simulation for Net Present Value (NPV) that plots a NPV curve and some probabilities using ggplot. It comes out well. The same code and same seed, when run under Shiny, the output is not the same. That is, the nature of the curve is the same; but, it is shifted left on x-axis.

Can you please suggest some tips why this might be happening?

I think, this is not really the right forum for 'application development' questions. But, I didn't get a favorable response elsewhere (http://stackoverflow.com/q/43567385/919480) ; hence the question.

**Comment by fereshtehRS** [comment]
Did you post your question to `shiny` forum:

https://groups.google.com/forum/#!forum/shiny-discuss

**Comment by ProgramErgoSum** [comment]
Just did; let's see.
