### ISSUE TITLE
R markdown dynamic user inputs only rendering at first time in browser

### ISSUE THREAD

**Issue by faigl** [rstudio/shiny-server#295]
Hi, 

R markdown documents with shiny runtime elements are rendering well  only first time, when launched by a user. E.g., when launched from Rstudio, or when accessed first time from external browser at shiny server.

If someone opens the document from a new browser, or just reloads the page in the same browser, shiny runtime elements are missing.

I also experienced that if the .Rmd file content is changed, e.g., a new empty line is added in the R code chunk, the reload will work fine. 

Do you now any solution to this problem, how to achieve that the page reloads well, without modifying the .Rmd file?

similar issues:
   @jfredtx mentioned in https://github.com/rstudio/flexdashboard/issues/108 

[test.Rmd.txt](https://github.com/rstudio/shiny-server/files/1074647/test.Rmd.txt)

BR,
Zoltan

**Comment by SchultzBen** [comment]
Hi,

Having the same problem as above. Interestingly only on the first view does the page properly render, on subsequent views shiny elements are missing, even when opened on different machines.

Btw. I am using Shiny Server v1.5.1.834 if it makes any difference.

Thanks in advance.

BR,
Benedek

**Comment by fereshtehRS** [comment]
@faigl See if the attached modified version of your document makes any difference:

[test-modified.Rmd.txt](https://github.com/rstudio/shiny-server/files/1074724/test-modified.Rmd.txt)

**Comment by faigl** [comment]
Many thanks, it solved the issue. 

There was still one small bug:
    ':' is not needed after html_output, only if someone adds additional html_output parameters, like theme, css, etc., one level indented.

So the good working example is the attached file.

Now I see that the "runtime" parameter should come outside the scope of "output" parameter, in fact this is written in the docs: http://rmarkdown.rstudio.com/authoring_shiny.html 

[test-modified.Rmd (1).txt](https://github.com/rstudio/shiny-server/files/1074824/test-modified.Rmd.1.txt)

**Comment by fereshtehRS** [comment]
@faigl glad that it is working for you.

**Comment by nmooman** [comment]
In case you have 
---
title: "Test Dashboard"
runtime: shiny, **_html_**
output: 
  flexdashboard::flex_dashboard:
    orientation: column
    theme: 'cerulean'
---

Git rid of html part from the runtime:
So, you will have as
_---
title: "Test Dashboard"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: column
    theme: 'cerulean'
---
AM

**Comment by marfisica** [comment]
I am facing the same problem. With suggestion I managed to make it work correctly by RStudio's native browser. However, in conventional browse (chormer, IE, etc.) everything that has reactivity does not work. What can it be? Sorry for the horrible English.

**Comment by ItafHamrouni** [comment]
Hello,
try to put runtime: shiny under the title directly. I hope it helps
