### ISSUE TITLE
Shiny on R Studio Server Reactivity not working from different host

### ISSUE THREAD

**Issue by bedantaguru** [rstudio/shiny-server#302]
Kindly refer to https://github.com/rstudio/shiny/issues/1773

As mentioned in the above link I have a CentOS 6.7 machine with both RStudio Server and Shiny Server. When I was developing a shiny app in RStudio Server it is losing it's reactive nature in other host (when Rstudio is opened from other client machines in same network.) but it's working in same host.

**Comment by jcheng5** [comment]
From the other issue, it looks like you're not actually using Shiny Server? Shiny Server is a different piece of software, distinct from RStudio Server and from the Shiny package. The other issue referred to RStudio Server. If indeed you're not using Shiny Server then I'll just answer on the other issue.
