### ISSUE TITLE
mathjax CDN

### ISSUE THREAD

**Issue by alpapan** [rstudio/shiny-server#321]
Hello

shiny 1.0.5 from the RStudio's Ubuntu installers

```
uname -a
Linux  4.4.0-93-generic #116~14.04.1-Ubuntu SMP
```

I'm having the same issue with the MathJax CDN as reported in the Rmarkdown:
https://github.com/rstudio/rmarkdown/issues/1014

relevant error :

```
Access to Font at 'https://mathjax.rstudio.com/2.7.2/fonts/HTML-CSS/TeX/woff/MathJax_Main-Regular.woff?V=2.7.2' from origin 'https://myserveraddress' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://myserveraddress' is therefore not allowed access.
```

Hopefully the fix will be similar?

thanks
a

**Comment by alpapan** [comment]
relevant error :

```
Access to Font at 'https://mathjax.rstudio.com/2.7.2/fonts/HTML-CSS/TeX/woff/MathJax_Main-Regular.woff?V=2.7.2' from origin 'https://myserveraddress' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://myserveraddress' is therefore not allowed access.
```

**Comment by alpapan** [comment]
I can confirm this issue is also happening with the github master (commit 5aca0ba)

**Comment by jjallaire** [comment]
@jspiewak Did anything change in our mathjax mirror?

**Comment by jspiewak** [comment]
Not that I am aware of.

The issue in rstudio/rmarkdown#1014 was when we were serving a redirect to MathJax at cdnjs, which we solved by hosting the content ourselves.

@alpapan could you say more about how you are running Shiny server (any configuration changes you have made) and what browser you are using to access it (perhaps [include a HAR of the page load](https://developers.google.com/web/tools/chrome-devtools/network-performance/reference#export_requests_data))

**Comment by alpapan** [comment]
Hello

Using Shiny git 5aca0ba on an ubuntu 14.04 via an apache proxy on another server

```
# cat /etc/shiny-server/shiny-server.conf
# Instruct Shiny Server to run applications as the user "shiny"
run_as shiny;

app_init_timeout 120;
app_idle_timeout 120;

# Define a server that listens on port 3838
server {
  listen 3838;

  # Define a location at the base URL
  location /rshiny {

    # Host the directory of Shiny Apps stored in this directory
    #site_dir /srv/shiny-server;
    site_dir /scratch_cory/sysadmin/shiny-apps;

    # Log all Shiny output to files in this directory
    log_dir /var/log/shiny-server;

    # When a user visits the base URL rather than a particular application,
    # an index of the applications available in this directory will be shown.
    directory_index on;
  }
}
```

Here is a link... hope it helps!
https://gpi.westernsydney.edu.au/rshiny/rnaseq/DEApp/

**Comment by wch** [comment]
This is what I see when I visit https://gpi.westernsydney.edu.au/rshiny/rnaseq/DEApp/, and it looks correct to me:

![image](https://user-images.githubusercontent.com/86978/31088784-816958f6-a767-11e7-8a4a-ffb52681b790.png)

**Comment by rfilmyer** [comment]
I ran into this issue when knitting a document using rstudio and trying to open it using Chrome. the font loads are being blocked because of [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS), and thus mathjax doesn't render mathematical symbols.

However, I do not think this is specifically a bug with Shiny. Instead, I think this is actually an issue with rstudio.com's mathjax hosting. I'm not very skilled with working with CORS stuff, but I imagine the admins would want to put an `Access-Control-Allow-Origin: *` header for these specific files:

```
https://mathjax.rstudio.com/latest/fonts/HTML-CSS/TeX/woff/MathJax_Main-Regular.woff?V=2.7.2
https://mathjax.rstudio.com/latest/fonts/HTML-CSS/TeX/woff/MathJax_Math-Italic.woff?V=2.7.2
https://mathjax.rstudio.com/latest/fonts/HTML-CSS/TeX/woff/MathJax_Size1-Regular.woff?V=2.7.2
```

**Comment by jjallaire** [comment]
@jspiewak Is this something we can do?

**Comment by jspiewak** [comment]
@jjallaire I had thought we had enabled CORS already, and that it had been verified. I have double checked, and tweaked a couple of the settings. Could someone verify a) the tweaks didn't break anything and b) that the tweaks resolve this issue?
