### ISSUE TITLE
Error getting worker; application exited during initialization

### ISSUE THREAD

**Issue by jwhendy** [rstudio/shiny-server#323]
I'm having what I think is a firewall issue. I have `shiny-server` on my Amazon EC2 server and it's been working fine. I updated an app today and am not able to load it while on my corporate network or while on my corporate VPN.

Unfortunately, I don't know if the old version was still working prior to updating. It might be something new in my code/permissions, or it might be a change in the firewall.

[Here is the app](http://52.36.187.23/insurance-viz/). The behavior I see is that the UI pops up as expected, but the graph/table never come through and it turns gray like a dead server.

If I go to the top level, I get [this](https://imgur.com/BpXCMZo) for the index/demo. So the page renders, but the embedded `shiny` stuff fails.

I *thought* it might be a file permissions issue, since I copied the old app folder to a different directory and simply `sudo cp -r ./dir /srv/shiny-apps/dir` to create the new one. I found [this page](https://www.r-bloggers.com/deploying-your-very-own-shiny-server/) and applied the permissions there... not sure if that's appropriate, but seemed like a possibility. I don't see any difference in the behavior.

Here's the output of `systemctl status`:
```
● shiny-server.service - ShinyServer
   Loaded: loaded (/etc/systemd/system/shiny-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2017-10-24 11:59:48 CDT; 1min 31s ago
  Process: 1727 ExecStopPost=/bin/sleep 5 (code=exited, status=0/SUCCESS)
  Process: 1734 ExecStartPost=/bin/sleep 3 (code=exited, status=0/SUCCESS)
 Main PID: 1735 (shiny-server)
    Tasks: 11
   Memory: 38.6M
      CPU: 961ms
   CGroup: /system.slice/shiny-server.service
           ├─1733 /bin/bash -c /opt/shiny-server/bin/shiny-server --pidfile=/var/run/shiny-server.pid >> /var/log/shiny-server.log 2>&1
           └─1735 /opt/shiny-server/ext/node/bin/shiny-server /opt/shiny-server/lib/main.js --pidfile=/var/run/shiny-server.pid

Oct 24 12:00:33 ip-xxx-xx-xx-xxx su[1761]: pam_unix(su:session): session opened for user ubuntu by (uid=0)
Oct 24 12:00:34 ip-xxx-xx-xx-xxx su[1789]: Successful su for ubuntu by root
Oct 24 12:00:34 ip-xxx-xx-xx-xxx su[1789]: + ??? root:ubuntu
Oct 24 12:00:34 ip-xxx-xx-xx-xxx su[1789]: pam_unix(su:session): session opened for user ubuntu by (uid=0)
Oct 24 12:00:53 ip-xxx-xx-xx-xxx su[1805]: Successful su for ubuntu by root
Oct 24 12:00:53 ip-xxx-xx-xx-xxx su[1805]: + ??? root:ubuntu
Oct 24 12:00:53 ip-xxx-xx-xx-xxx su[1805]: pam_unix(su:session): session opened for user ubuntu by (uid=0)
Oct 24 12:01:00 ip-xxx-xx-xx-xxx su[1821]: Successful su for ubuntu by root
Oct 24 12:01:00 ip-xxx-xx-xx-xxx su[1821]: + ??? root:ubuntu
Oct 24 12:01:00 ip-xxx-xx-xx-xxx su[1821]: pam_unix(su:session): session opened for user ubuntu by (uid=0)
```

My log has repeats of this:
```
[2017-10-24 11:19:23.486] [WARN] shiny-server - No host header sent by user-agent masscan/1.0 (https://github.com/robertdavidgraham/masscan)
[2017-10-24 11:48:24.516] [INFO] shiny-server - Error getting worker: Error: The application exited during initialization.
[2017-10-24 11:48:25.150] [INFO] shiny-server - Error getting worker: Error: The application exited during initialization.
[2017-10-24 11:59:40.190] [INFO] shiny-server - Stopping listener on 0.0.0.0:80
[2017-10-24 11:59:40.190] [INFO] shiny-server - Shutting down worker processes (with notification)
[2017-10-24 11:59:46.323] [INFO] shiny-server - Shiny Server v1.5.5.872 (Node.js v6.10.3)
[2017-10-24 11:59:46.326] [INFO] shiny-server - Using pidfile /var/run/shiny-server.pid
[2017-10-24 11:59:46.328] [INFO] shiny-server - Using config file "/etc/shiny-server/shiny-server.conf"
[2017-10-24 11:59:46.380] [INFO] shiny-server - Starting listener on 0.0.0.0:80
[2017-10-24 12:00:34.015] [INFO] shiny-server - Error getting worker: Error: The application exited during initialization.
```

I also have various instances of the `WARN` message about  host headers. Guessing this is just different browsers trying to access?
```
[2017-10-22 03:04:48.536] [WARN] shiny-server - No host header sent by user-agent masscan/1.0 (https://github.com/robertdavidgraham/masscan)
[2017-10-22 19:01:42.568] [WARN] shiny-server - No host header sent by user-agent Telesphoreo
[2017-10-23 03:30:08.566] [WARN] shiny-server - No host header sent by user-agent undefined
[2017-10-23 18:28:36.765] [WARN] shiny-server - No host header sent by user-agent sysscan/1.0 (https://github.com/robertdavidgraham/sysscan)
```

Here's my config. I bumped the timeout from 500 to 2000 just to see if it's the VPN round trip, but that didn't change anything. I set this up maybe 2 years ago and noted that I have `ubuntu` as the user... is that an issue? I tried making it `shiny` and things wouldn't even load.
```
$ cat /etc/shiny-server/shiny-server.conf 
# Instruct Shiny Server to run applications as the user "shiny"
run_as ubuntu;

# Define a server that listens on port 3838
server {
  listen 80;

  # Define a location at the base URL
  location / {

    # Host the directory of Shiny Apps stored in this directory
    site_dir /srv/shiny-server;

    # Log all Shiny output to files in this directory
    log_dir /var/log/shiny-server;

    # When a user visits the base URL rather than a particular application,
    # an index of the applications available in this directory will be shown.
    directory_index on;
    app_init_timeout 2000;
  }
}
```

Many thanks for suggestions of where to look further! I noted this is the same error as #153, but that was due to an address already in use, whereas this doesn't appear to be.

**Comment by fereshtehRS** [comment]
@jwhendy 

Is [this](http://52.36.187.23/insurance-viz/)  still the app you are having issue with? I am seeing this:


![shiny-app](https://user-images.githubusercontent.com/4906984/31961601-25466c08-b8c9-11e7-9a3f-cda6a220ab5e.png)

seems to be functional. Even the top level of your link works for me.

**Comment by jwhendy** [comment]
Not surprising. Note from my post, emphasis added:

> I updated an app today and am not able to load it **while on my corporate network or while on my corporate VPN**...  It might be something new in my code/permissions, or **it might be a change in the firewall.**

I realize this is tough to troubleshoot as you can't replicate my internet settings, but I was hoping the logs could help point to something or someone familiar with `shiny-server` could point me in the direction of where to further look.

For example, it's serving a web page, but *not* able to show the `shiny` stuff, as shown in the [screenshot](https://imgur.com/BpXCMZo) (which I also used because I realize others can't replicate).

Hope that helps clarify!

**Comment by fereshtehRS** [comment]
@jwhendy I just wanted to be sure that what I am accessing is still the same application that you are having problem with. So the issue is only from within your corporate network. It would be difficult to troubleshoot, as you mentioned.

The following might help:

1- Open browser console before accessing the application. You might see where the failure/disconnect happens.

2- Check `/var/log/shiny-server` directory on the server for the most recent application log file associated with this particular application. Application-specific errors would be logged in these files. I doubt you find anything useful since the app is running fine in general. But doesn't hurt to do so.

3- Try accessing this application from your corporate network:

http://shiny.rstudio.com/gallery/authentication-and-database.html 

see if the app loads after you login (login info on side panel).

4- Capture a HAR file when accessing your application:

https://www.inflectra.com/support/knowledgebase/kb254.aspx

**Comment by jwhendy** [comment]
Gotcha. Yes, that's the app indeed. I should have included a screenshot of what I see from corporate internet/VPN just to clarify.

![image](https://user-images.githubusercontent.com/379357/31966955-f7148d2a-b8d1-11e7-925f-9f0e6c4033b0.png)


1: I see this in the console:
```
VM180:161 WebSocket connection to 'ws://52.36.187.23/insurance-viz/__sockjs__/n=IuFkvDmNbQLhXQpgp3/078/9yewb74q/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
WrappedWebSocket @ VM180:161
y.websocket @ sockjs-0.3.4.min.js:27
y._try_next_protocol @ sockjs-0.3.4.min.js:27
y._didClose @ sockjs-0.3.4.min.js:27
f._ir.onfinish @ sockjs-0.3.4.min.js:27
f.emit @ sockjs-0.3.4.min.js:27
f.onfinish @ sockjs-0.3.4.min.js:27
f.emit @ sockjs-0.3.4.min.js:27
g.xhr.onreadystatechange @ sockjs-0.3.4.min.js:27
```

2: I'll check the log later tonight (can't ssh to my AWS instance from the corp network either!).

3: That application works with a variety of logins. That's promising right?? What might be different between that server and mine? For reference, I have `shiny-server` listening on 80, and my EC2 permissions allow access on port 80 from `0.0.0.0` (anywhere).

4: I captured a HAR file. I'm not familiar with all of the data in there... should this be kept confidential/submitted to some support address vs. open on the web? The failure occurs in the `websocket` process (same general indication as the console):
```
Request URL:ws://52.36.187.23/insurance-viz/__sockjs__/n=gfgjUczNUOMWDR264f/354/5uqd82m7/websocket
Request Method:GET
Status Code:400 Bad Request
Response Headers
view source
```

Thanks a bunch! I realize this is hard to troubleshoot, so many thanks for taking a stab at it...

**Comment by fereshtehRS** [comment]
3- At least we know that the issue is just against your server.

4- You can attach the HAR file in an email to me: fereshteh@rstudio.com

A couple of other things to try:

5- To eliminate the possibility that the new version of Shiny Server caused this, install the older version and see if the app is accessible.

6- When you bring up the application, on the browser page, use these keys together: Ctrl+Alt+Shift+A . This will bring up a page with a list of protocols. Start from the top, and one-by-one deselect them. And every time refresh the page. You might have an issue with a specific protocol, and this way you can find the problematic protocol.

**Comment by jwhendy** [comment]
4: done!

5: will do, along with checking logs per **2** above.

6: Woah! Cool and this was the winning combo, so deselecting `xhr-streaming`, then refreshing, worked. What does that indicate (other than that you rock!)?

![image](https://user-images.githubusercontent.com/379357/31969902-e3a2cc48-b8db-11e7-8fac-0532bced94b7.png)

**Comment by fereshtehRS** [comment]
That is great :)
We know there are variations on how different protocols behave in different network settings, and it is hard to tell what is really causing it without knowing more about your environment. That is why we have this little troubleshooting tool.

I point you to the Admin Guide section on protocols:

http://docs.rstudio.com/shiny-server/#specifying-protocols

I believe this feature also works on the open source version of Shiny Server. You can disable certain protocols on the server side when you determine that as a valid/acceptable solution.

**Comment by jwhendy** [comment]
Hmmm. So, I *think* I did that correctly and added this line:
```
disable_protocols websocket xdr-streaming xhr-streaming;
```

Unfortunately, the behavior isn't what I expected. All protocols are shown checked, despite the three I disabled being gray like they shouldn't be an actual option.
![2017-10-24_204700](https://user-images.githubusercontent.com/379357/31976350-abf38320-b8fc-11e7-8019-49d839cc7857.png)

I stumbled on the `disable websockets;` option and added that for good measure, but get the same result. The admin guide wording was confusing to me though. Note these statements, which appeared to contradict themselves (from my reading):

**3.8: Specifying protocols**
>If you would like to omit one or more of these protocols from the list, you can currently do so only from the client (we hope to make a server-side configuration available in a future release of Shiny Server).

**3.8.1: Disabling websockets on the server**
>...some environments have found consistent problems with having particular protocols enabled [...] In this case, you can use the `disable_protocols` setting to disable any of the available protocols.

The first sounded like this only works from the client side, but there are 1:1 matched options that *sound* like they're intended to do the same from the server side.

You were right about the logs: they look fine (guessing they only get made on successful access). I'll try the older `shiny-server` version route. I noticed that when I `Ctrl-Shift-Alt-c` on that example from the `shiny` gallery you sent, the options look different. Maybe it's running an older version? Note staggered vs. one per row:

![2017-10-24_205653](https://user-images.githubusercontent.com/379357/31976565-e60c9bf4-b8fd-11e7-98bb-1de782fe511a.png)

**Comment by jwhendy** [comment]
Traced to the version! I did a binary search on [rstuido ubuntu .debs](https://download3.rstudio.org/) and ended up finding that `1.4.2.789` is the last release that works. The next apparent release, `1.4.4.800` does not (didn't see anything between these two).

I think I'll close this and thank you *soooo much* for all the assistance and troubleshooting. Hopefully tracking down the specific release can give insights to developers about what might and might not work well with `shiny` apps and firewalls.

**Comment by fereshtehRS** [comment]
@jwhendy Thanks for trying different versions; this is very useful info.

Just to clarify how protocol selections or disabling works:
- When you disable any protocol on the server side, we do not remove it from the UI selection. What you see on the UI is confusing, but in fact the options that are greyed out are not being used. The way you have configured it (based on the UI image) should work in your environment. If it doesn't, then that is a discrepancy between what you were seeing before disabling on client side, and then disabling on server side.
`disable websockets;` is another option, just to disable one protocol. We started with that since `websockets` seemed to be problematic in some environments. Then we added the ability to disable any number of protocols.

Thank you for sing Shiny Server, and best of luck to you!

**Comment by jwhendy** [comment]
Hmmm. So the config options on the server *should* have replicated unchecking those same three boxes on the client side? If so, indeed that did not seem to work for some reason. At this point, I'm happy that it works so I think I'll leave it alone! Thanks again.
