### ISSUE TITLE
Error message: Too Many Users

### ISSUE THREAD

**Issue by skranz** [rstudio/shiny-server#326]
I have developed a shiny app that allows interactive quiz questions in a lecture - more than 100 students log-in simultaneously to the website with their mobile phones. However, some students could not log in but got an error page:
```
Too Many Users

Sorry, but this application has exceeded its quota of concurrent users. Please try again later.
```
The error message seems to originate here:
https://github.com/rstudio/shiny-server/blob/cf0bf138a0ea38ba803ad96a6fef10ccd65f4ff9/lib/core/render.js#L133

Yet, I have no idea, why I get this error. Is there some fixed limit of concurrent users in shiny server open? Is it just a hardware limitation of my server?

My web search found only references to such a limit for concurrent user for shiny-server pro, e.g. https://support.rstudio.com/hc/en-us/articles/220760228-Concurrent-Users-in-Shiny-Server-Pro.
Yet, I could not find any documentation on such limits for shiny server open.

My shiny app runs with shiny-server open based on a docker container extending rocker/shiny.

I guess as workaround, I will try splitting the application into several identical apps, yet I wonder why the error arises.

**Comment by pmcharrison** [comment]
I am experiencing this problem too, on Shiny Server Open.

**Comment by fereshtehRS** [comment]
You are hitting the default max value of `simple_scheduler` which is 100.

**Comment by skranz** [comment]
Thanks  a lot for the info. Searching for `simple_scheduler` indeed yielded the description in Section 3.1.2 of the shiny-server documentation (maybe one could add in the documentation that the default limit is 100 concurrent users). I will then adapt my shiny-server.conf file as below to raise the number of concurrent users to 500:

```
run_as shiny;
# Define a new location at the base URL
location / {
  # Allow 500 concurrent connections
  simple_scheduler 500;
  
  ...
}
```

**Comment by pmcharrison** [comment]
Thanks, this worked for me.

**Comment by jcheng5** [comment]
@skranz Does your quiz work pretty well with >100 users connected? If not, our [Academic Discount policy](https://www.rstudio.com/pricing/academic-pricing/) offers a free license of Shiny Server Pro for teaching purposes.

**Comment by skranz** [comment]
@jcheng5 I could not yet check, whether it works fine with more than 100 users (the number of students in class tends to drop a bit during the semester, so I may not hit the 100 participant mark again this semester). If I still encounter some problems, I will keep the issue updated.

Thanks for the hint of the free Academic Shiny Server Pro license. That is a great offer by RStudio, in addition to all the great open source software that you provide. I may test Shiny Server Pro, if the `simple_scheduler` does not turn out to be sufficient for my quiz app. Yet, my hunch would be that a single R process (as provided by shiny server open) should be sufficient for my app, which I tried to structure in a way that an additional user should not cost much extra computation resources.

 (In addition, before testing Shiny Server Pro, I would have to inform myself how easy it is to use Shiny Server Pro with a public docker container on Docker Hub. Is it at all allowed / possible to put Shiny Server Pro in a public docker container? Can I extend the official rocker/shiny container or is there some other official container for Shiny Server Pro?)

**Comment by sylfree9999** [comment]
@jcheng5 I'm a little bit confused. Does @skranz fits the 100 concurrent user scenario? Does Shiny Server Open Source support that? As my understanding, R can only serve a connection at a time. Will those 100 concurrent users in the Shiny Server Open stuck since they will have to wait other users to finish their R computations and release the resource?

**Comment by jcheng5** [comment]
R can have many concurrent connections. However, at any given instant, R can only perform one computation (unless you use the brand new async features, which are there if you need them). If your app is highly optimized you may be able to serve 100 concurrent users on a single app with Shiny Server Open Source. We're currently working on load testing tools for Shiny that will let you make this determination empirically.

**Comment by sylfree9999** [comment]
@jcheng5  Thanks for the great news, I will certainly give it a try.
One more question, if the shiny app is currently running a long-process R computation, the other user is not even able to open the shiny app. Is there a way to check whether the shiny server can respond to request so that I can redirect the user to another page?

**Comment by chintanp** [comment]
@jcheng5 

> 
> 
> R can have many concurrent connections. However, at any given instant, R can only perform one computation (unless you use the brand new async features, which are there if you need them). If your app is highly optimized you may be able to serve 100 concurrent users on a single app with Shiny Server Open Source. We're currently working on load testing tools for Shiny that will let you make this determination empirically.

Are there any updates on the load testing tools that you mention? We want to determine which model of Shiny app deployment would be suitable for our project.

**Comment by jcheng5** [comment]
Sure, they’re here: https://rstudio.github.io/shinyloadtest/
