### ISSUE TITLE
in linux local R runApp is OK,but failed when i put it on server

### ISSUE THREAD

**Issue by gaoyunpeng111** [rstudio/shiny-server#333]
I totally do it as README.md

**Comment by shrektan** [comment]
You should paste the log or other information so that people can help you. Also, it's better to ask such questions in [StackOverflow](https://stackoverflow.com) ... 😢

**Comment by wch** [comment]
Yes, StackOverflow is a better place for this kind of question.

**Comment by gaoyunpeng111** [comment]
@shrektan
thanks for your advise,I have solved
