### ISSUE TITLE
Application Logs to Standard Out

### ISSUE THREAD

**Issue by ef2240** [rstudio/shiny-server#355]
I'm running Shiny Server inside a docker container on a Kubernetes cluster. The cluster uses a suite of logging and monitoring tools (including Sumo Logic and New Relic). However, I can't really utilize these tools because the logs that I care the most about, the application error logs, are written to a log file and not standard out, as the Server log is. Even ad hoc monitoring using `docker log` or `kubectl log` is impossible. Is it possible to route the application logs to standard out?

**Comment by vromero** [comment]
Same problem here.

**Comment by stevenranney** [comment]
Having similar issues here. 

I tried using the answer [provided in this StackOverflow Q/A](https://stackoverflow.com/questions/48864028/logging-json-to-stdout-in-shiny-server) to force the log in `/var/log/shiny-server` to `STDOUT` but this still does not work.

**Comment by llealgt** [comment]
Same problem here, have you guys found a workaround ?

**Comment by jcheng5** [comment]
You tried the `xtail` solution in the stackoverflow link above? We've had users report success with that.

**Comment by llealgt** [comment]
no, unfortunately i'm in centos and even though i  searched, i could not find xtail(or equivalent ) for centos.

**Comment by vromero** [comment]
Although there is for sure some kind of hack to make it work with `xtail`, it wouldn't represent the most adequate solution as it would mean docker will be monitoring `xtail` instead of shiny itself, hence the stability would be compromised. Also in general, one docker container should only contain one running process with no daemons, no init, etc.

**Comment by thomasfedb** [comment]
Also looking for this feature for deployment of Shiny apps

**Comment by jcheng5** [comment]
As of Shiny Server 1.5.13, this is now available as a feature. Set the environment variable `SHINY_LOG_STDERR=1` at runtime to enable.

**Comment by qm994** [comment]
> As of Shiny Server 1.5.13, this is now available as a feature. Set the environment variable `SHINY_LOG_STDERR=1` at runtime to enable.

Hey @jcheng5  I know in shiny server. 1.5.13 we have the SHINY_LOG_STDERR=1 to enable the logs as stderr. I just updated my shiny server to the latest version and set this env as (1) runtime docker; (2) in the shiny-server.sh file, but both ways wont work for me. Could u elaborate a little bit about `Set the environment variable SHINY_LOG_STDERR=1 at runtime`. 

Here is how I did in shiny-server.sh file: 
```
#!/bin/bash
sed -i '1ienv SHINY_LOG_STDERR=1' /etc/init/shiny-server.conf
sed -i '1ienv SHINY_LOG_LEVEL=ERROR' /etc/init/shiny-server.conf
# Make sure the directory for individual app logs exists
mkdir -p /var/log/shiny-server
chown shiny:shiny /var/log/shiny-server

# # push the "real" application logs to stdout with xtail
exec xtail /var/log/shiny-server/ & exec shiny-server 2>&1 
```

**Comment by jcheng5** [comment]
@qm994 Try this instead:

```bash
#!/bin/bash
# Make sure the directory for individual app logs exists
mkdir -p /var/log/shiny-server
chown shiny:shiny /var/log/shiny-server

# # push the "real" application logs to stdout with xtail
SHINY_LOG_STDERR=1 SHINY_LOG_LEVEL=ERROR exec shiny-server 2>&1

**Comment by qm994** [comment]
> ```shell
> SHINY_LOG_STDERR=1 SHINY_LOG_LEVEL=ERROR
> ```

hey thanks for the reply @jcheng5 ! I have tested them all and unfortunately they still wont work for me: 
for first one `SHINY_LOG_STDERR=1 SHINY_LOG_LEVEL=ERROR exec shiny-server 2>&1 ` it wont create the env variables at all; and it wont pass the error logs to `/var/log/shiny-server.log` and the the file `/var/log/shiny-server.log` was actually missing;

for passing them with docker ENV and docker run -e: yes, it will create the env variables, but unfortunately this wont create the `/var/log/shiny-server.log`  file also. Also the application logs in `/var/log/shiny-server/****.log` still very detailed and not transform to verbose ERROR.

**Comment by qm994** [comment]
Oh I probably forgot to mention i am using the open source shiny server. So not sure if this new feature is only target for pro or available for both

**Comment by jcheng5** [comment]
@qm994 This applies to Shiny Server Open Source as well. Can you create a reprex so I can try it myself?

**Comment by jcheng5** [comment]
> yes, it will create the env variables, but unfortunately this wont create the /var/log/shiny-server.log

Then instead of `exec shiny-server 2>&1`, perhaps use `shiny-server 2>&1 | tee -a /var/log/shiny-server.log` (note the lack of `exec`; I believe this is necessary for the `|` operator to work)


> Also the application logs in /var/log/shiny-server/****.log still very detailed and not transform to verbose ERROR.

The `SHINY_LOG_LEVEL` environment variable only affects the messages coming from Shiny Server itself (/var/log/shiny-server.log), not the messages coming from the individual R processes (/var/log/shiny-server/*.log). As the latter are literally just the stderr of the R process, we don't have enough information to know what lines are errors vs warnings vs info, etc.
