### ISSUE TITLE
Enable gzip compression

### ISSUE THREAD

**Issue by trestletech** [rstudio/shiny-server#38]
> Right now it takes quite a long time to load the initial page + static resources, especially over slow connections. I was hoping that somebody could add a feature where shiny could be configured to use gzip when the client indicates Accept-Encoding: gzip.

**Comment by laoyang945** [comment]
Hi I am wondering whether this enhancement has been implemented? thanks!

**Comment by jdonnell01** [comment]
Hi, was this enhancement to allow for gzip compression ever enabled in Shiny Server?

**Comment by jcheng5** [comment]
Yes, and it defaults to true.
