### ISSUE TITLE
getwd() seems to return NULL occasionally on shiny server

### ISSUE THREAD

**Issue by stefanoborini** [rstudio/shiny-server#408]
Not sure if this is due to my organisation configuration of shiny server, but in my deployment I attempt to retrieve the current directory with getwd() at the very beginning of the app.R file. Occasionally, this returns NULL, but I've seen it return the actual path to the deployed application occasionally. I was unable to identify a pattern, but you might have some ideas.

More in general, is there a way to obtain the current deployment root path?

**Comment by jcheng5** [comment]
I'm not sure why this would happen--the only cases I'm aware of where `getwd()` returns `NULL` is where the underlying directory is deleted while the process is running. I don't know why/how that would be the case while an app is just starting up.

**Comment by jcheng5** [comment]
Oh, I see your comment now on the rstudio/shiny issue. I don't think the 404 guarantees that the subprocess is deleted, only that Shiny Server won't bother even looking for existing processes if it doesn't see the directory on disk; but if the directory on disk exists, then it may match against an existing process, even one that was started before the directory was removed.

In any case, putting/touching restart.txt in the app directory will force sessions going forward to use a new process. https://docs.rstudio.com/shiny-server/#restarting-an-application
