### ISSUE TITLE
incorrect checksum for node

### ISSUE THREAD

**Issue by fvalenduc** [rstudio/shiny-server#423]
It seems the checksum listed in external/node/install-node.sh is incorrect. Therefore the installation of node fails and the 2 subsequent commands to installation of the node modules also fail. If I correct the checksum to bfde561278fbf3a9c8e3c5bb297eeacb2b2988f9ed63651952754d66884ef4d7, it works. However, it seems the version downloaded with the script doesn't seems the same as the one available in https://nodejs.org/dist/v12.14.0/.

**Comment by jcheng5** [comment]
Whoops--thanks for the report!

The nodejs.org binaries don't support Red Hat 6 anymore, so we have to build our own.
