### ISSUE TITLE
The conflicts between index and apps

### ISSUE THREAD

**Issue by jacobxk** [rstudio/shiny-server#426]
I found that if I put a `Rmarkdown` file (e.g., index.Rmd) into the `/srv/shiny-server` folder (or other site directory specified in the configuration file) and then:

1. the `Rmarkdown` file can be rendered correctly, but all the apps in other folders in the subdirectory would be "not found"
2. if I change the `Rmarkdown` file into a pre-rendered single `html` file (e.g., index.html), everything goes fine.

I don't know if this is on purpose but it did confuse me in the last several days.

My shiny-server version is 1.5.12.933.

**Comment by jacobxk** [comment]
Not working as expected:
```sh
drwxr-xr-x 2 root root 4.0K Jan  6 05:17 ct-accuracy
drwxr-xr-x 2 root root 4.0K Jan  6 05:17 ct-pilot
-rw-r--r-- 1 root root  989 Jan  6 06:04 index.Rmd
drwxr-xr-x 2 root root 4.0K Jan  6 05:17 unit-demo
```

Everything goes fine:
```sh
drwxr-xr-x 2 root root 4.0K Jan  6 05:17 ct-accuracy
drwxr-xr-x 2 root root 4.0K Jan  6 05:17 ct-pilot
-rw-r--r-- 1 root root 4.2M Jan  6 05:26 index.html
drwxr-xr-x 2 root root 4.0K Jan  6 05:17 unit-demo
```

**Comment by jcheng5** [comment]
This is indeed on purpose; when you place an index.Rmd within a directory, the entire directory and all subdirectories are considered to be supporting files for that .Rmd, and cannot be accessed directly. This is to prevent potentially proprietary information (like the .rds files above, or any R source code) from being downloadable by clients.

If you must have this kind of setup, you can set up individual `location` directives in your /etc/shiny-server/shiny-server.conf file for each of the subdirectories. (If you go this route, be aware that the order of the `location` directives matter; I think the more-specific locations should be specified first.)
