### ISSUE TITLE
Shiny Server Pro source

### ISSUE THREAD

**Issue by sjmulder** [rstudio/shiny-server#446]
It is my understanding that Shiny Server Pro is a derivative work of Shiny Server, including contributions made to this repository under the AGPL3. Unless copyright was reassigned by those contributors (of which I found no evidence) those contributions are covered by AGPL3 as stated in section 5, point c of the license (emphasis added):

> c) You must license the entire work, as a whole, under this License to anyone who comes into possession of a copy. This License will therefore apply, along with any applicable section 7 additional terms, to the whole of the work, and all its parts, regardless of how they are packaged. **This License gives no permission to license the work in any other way, but it does not invalidate such permission if you have separately received it.**

Now I have downloaded the evaluation version of Shiny Server Pro, which as established above is covered under the AGPL3 and no other license if it incorporates contributions without copyright reassignment. Section 6 of the license states:

> You may convey a covered work in object code form under the terms of sections 4 and 5, provided that you also convey the machine-readable Corresponding Source under the terms of this License, in one of these ways:
>
> - a) [...] a physical product [...], accompanied by the Corresponding Source [...]
> - b) [...] a physical product [...] accompanied by a written offer [...] to give anyone who possesses the object code either (1) a copy of the Corresponding Source [...] on a durable physical medium [...] or (2) access to copy the Corresponding Source from a network server at no charge.
> - c) [...] from a designated place (gratis or for a charge), with a copy of the written offer to provide the Corresponding Source. [...]
> - d) [...] from a designated place (gratis or for a charge), and offer equivalent access to the Corresponding Source in the same way through the same place at no further charge. [...]
> - e) [...] using peer-to-peer transmission, provided you inform other peers where the object code and Corresponding Source of the work are being offered to the general public at no charge under subsection 6d.

Points (c) and (d) apply, given that the trial was distributed from an online source. However, I found no written offer for the source code (c) or a download link (d).

Please either a) inform me where I can find the source, or b) assert that the Shiny Server Pro includes no contributions that are covered under the AGPL3 license.

Note that the source code would necessarily include any additional components of the derived work as the license provides no linking exception.

**Comment by jcheng5** [comment]
Hi there. All contributors to Shiny Server Open Source either were employees of RStudio at the time of their contributions; have a signed CLA on file with RStudio; or submitted a contribution that I deemed too trivial to meet the threshold of originality. (Or, in the case of the dependencies we build on, are offered under a license that is compatible with both AGPLv3 and SSP’s commercial license.)

I hope this answers your concerns. I am happy to reopen the issue if you have evidence of copyright holders’ rights being violated—this is a topic I take extremely seriously.

**Comment by sjmulder** [comment]
Completely satisfactory answer, thanks.
