### ISSUE TITLE
Is Shiny Server (open source) compatible with multithreading packages like Future?

### ISSUE THREAD

**Issue by D3SL** [rstudio/shiny-server#449]
Shiny Server documentation states the open source version can run a single R process. Does that render Shiny Server Open Source incompatible with the multi-process method of multithreading used by packages such as Furr/Future and Foreach? Or can multithreaded functions still intentionally create (and close) extra worker threads and assign them to cores as in an interactive session?

**Comment by jcheng5** [comment]
Those are totally fine. Shiny Server will launch up to one R process for each app to run Shiny, then those R processes can launch child processes if they want.

If you're going to use future in particular, you may want to get familiar with [promises](https://rstudio.github.io/promises/).

**Comment by D3SL** [comment]
Thank you for the clear explanation. To doublecheck I get it now: When Server Pro states it can create multiple R processes that's referring to automatically making a new process to serve the webapp itself, IE users 1-5 are served by R process #1 and users 6-10 by process #2. This is as opposed to alternative architectures entirely such as ShinyProxy which containerize the entire app, server, and session per-user.

That second sentence in your post would be fantastic even just copied and pasted into the official R Server documentation where it discusses R Processes.

**Comment by jcheng5** [comment]
> That second sentence in your post would be fantastic even just copied and pasted into the official R Server documentation where it discusses R Processes.

Sounds good, thanks for the suggestion.
