### ISSUE TITLE
Administrator's Guide has typo

### ISSUE THREAD

**Issue by jhk0530** [rstudio/shiny-server#457]
in 2.6 [Local App Configurations](https://docs.rstudio.com/shiny-server/#local-app-configurations), last paragraph.

Server administrators should be mindful that allowing application owners to specify their own scheduler **parmeters** has potential performance implications, ..

`parmeters` should be modified into `parameters`

Thanks.

**Comment by jcheng5** [comment]
This'll be fixed in the next release. Thanks!
