### ISSUE TITLE
Shiny-server on ARM64

### ISSUE THREAD

**Issue by paull71** [rstudio/shiny-server#458]
Hi,

Following these instructions to install shiny-server on ARM64, https://github.com/rstudio/shiny-server/wiki/Building-Shiny-Server-from-Source. I am working off node-v12.18.0-linux-arm64.tar.xz

At this stage of the instructions (cd .. && ./bin/npm install) I get this:

`
> shiny-server@1.5.14 install /home/username/shiny-server
> node-gyp rebuild

make: Entering directory '/home/username/shiny-server/build'
  CXX(target) Release/obj.target/posix/src/posix.o
  SOLINK_MODULE(target) Release/obj.target/posix.node
  COPY Release/posix.node
make: Leaving directory '/home/username/shiny-server/build'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
`
Going all the way to the end to this step: (sudo cp ../config/default.config /etc/shiny-server/shiny-server.conf). The machine tells me that there is nothing in /etc/ that is shiny-server

Can someone help?

**Comment by jcheng5** [comment]
Looks like you figured it out, but I added a step to the instructions to create the /etc/shiny-server directory before attempting that cp operation. Thanks!

**Comment by paull71** [comment]
Thanks Joe. Appreciate the prompt response. Will give it a go. Regards
