### ISSUE TITLE
Shiny apps do not display graphs

### ISSUE THREAD

**Issue by tillea** [rstudio/shiny-server#462]
Hi,
I was using shiny-server version 1.5.3.838 on a Debian 9 system.  After upgrading to Debian 10 even simple example apps stopped working.  So I installed the [latest deb](https://download3.rstudio.org/ubuntu-14.04/x86_64/shiny-server-1.5.14.948-amd64.deb) but there is no change.  This is for instance true for the example `052-navbar-example` (or any other example - just to name one) as well as all own applications.  The logs are locking pretty normal.
Any idea what I can do to track down this?
Kind regards, Andreas.

**Comment by jcheng5** [comment]
Try looking in your browser's JS console, there should be some messages there?

**Comment by tillea** [comment]
On Mon, Oct 12, 2020 at 05:34:37PM -0700, Joe Cheng wrote:
> Try looking in your browser's JS console, there should be some messages there?
That hint helped.  It turned out that r-cran-shiny in Debian 10 is trying to use the Debian installed jquery 3.x while that version if r-cran-shiny package actually needs jquery 1.x.  I was able to solve this by backporting the latest r-cran-shiny.
Kind regards, Andreas.
