### ISSUE TITLE
Shiny Server config param `google_analytics_id` does not support new Google Analytics IDs

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny-server#469]
Sometime in the past 1-2 years, Google Analytics changed from using the familiar `UI-XXXXXX` tracking ID to a new system that uses a different format `G-XXXXXXX`. I'm not very knowledgeable in Google Analytics so I don't fully undersatnd the specifics, but it seems that plugging in the new format into a shiny server config does not work. The required javascript is slightly different. I now need to add Google Analytics manually to each app's UI using the provided JavaScript code instead of being able to provide the tracking ID in the config.

More info: https://support.google.com/analytics/answer/9539598?hl=en

**Comment by ck37** [comment]
I've also found this to be the case.

The new tracking code looks like this:

```javascript
<script async src="https://www.googletagmanager.com/gtag/js?id=G-1234"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-1234');
</script>
```
