### ISSUE TITLE
Rcpp_precious_remove not provided by package Rcpp

### ISSUE THREAD

**Issue by qdread** [rstudio/shiny-server#492]
On our Shiny server we are experiencing an issue where all apps including packages depending on Rcpp now throw errors.

```
error: function 'Rcpp_precious_remove' not provided by package 'Rcpp'
```

According to the Rcpp developer mailing list (https://www.mail-archive.com/rcpp-devel@lists.r-forge.r-project.org/msg10226.html) it is recommended to update to Rcpp 1.0.7 to fix this. But I just updated it and still get the error. Is there some interaction with the shiny server that would cause this issue? And how might I be able to fix it?

This is the console log for sessionInfo as root on the shiny server after loading the Rcpp package:

```
root@shiny02:/var/log/shiny-server# Rscript -e "library(Rcpp); sessionInfo()"
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.7 LTS

Matrix products: default
BLAS:   /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US       LC_NUMERIC=C         LC_TIME=en_US
 [4] LC_COLLATE=en_US     LC_MONETARY=en_US    LC_MESSAGES=en_US
 [7] LC_PAPER=en_US       LC_NAME=C            LC_ADDRESS=C
[10] LC_TELEPHONE=C       LC_MEASUREMENT=en_US LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] Rcpp_1.0.7

loaded via a namespace (and not attached):
[1] compiler_4.0.3
```

**Comment by wch** [comment]
Do you have any packages installed in your Shiny user's account? If you have Rcpp installed there, it could take precedence over the one installed by the root user.

**Comment by qdread** [comment]
Yes, that turned out to be the solution. Thanks!!! 🥂
