### ISSUE TITLE
SHINY_GAID: Documentation

### ISSUE THREAD

**Issue by JohnCoene** [rstudio/shiny-server#512]
I do not see the use of the `SHINY_GAID` environment variable documented anywhere.

https://github.com/rstudio/shiny-server/blob/dcd2deda4bb3b075c810ed3c25e8b462f9a545c3/R/SockJSAdapter.R#L174

Perhaps it is meant not to be; may this be used/should this be documented?

Apologies if I missed the documentation.

**Comment by jcheng5** [comment]
It’s an internal environment variable that Shiny Server sets when you use this feature: https://docs.rstudio.com/shiny-server/#google-analytics
