### ISSUE TITLE
Encoding problem shiny app on Shiny Server

### ISSUE THREAD

**Issue by rwaaijman** [rstudio/shiny-server#520]
Hi rstudio,
with the new shiny-server version (v1.5.18.979) there seems to be a problem with encoding characters when loaded a file with source().
The app attached to this message is packed into rocker-shiny verse to illustrate the problem. This issue not only appears in shiny-verse 4.1.3, but also in other versions like 4.0.5.

[app.zip](https://github.com/rstudio/shiny-server/files/8403967/app.zip)

See more replies in:https://github.com/rocker-org/rocker-versioned2/issues/397

**Comment by rwaaijman** [comment]
LC_ALL=en_US.UTF-8 has to be set in docker.
For more info see: https://github.com/rocker-org/rocker-versioned2/issues/397

**Comment by eitsupi** [comment]
@rwaaijman Please do not close this issue. I'm not sure why this problem only occurs in scripts loaded with `source()`.

Also, the workaround is not to set `LC_ALL=en_US.UTF-8` but as described in the comments below.
https://github.com/rstudio/shiny-server/issues/304#issuecomment-313785524
