### ISSUE TITLE
Rendered `html` document from `qmd` not working on self-hosted Shiny Server

### ISSUE THREAD

**Issue by cutterkom** [rstudio/shiny-server#530]
Hey,

I want to deploy a Shiny interactive document written with Quarto on a self-hosted Shiny server (version Shiny Server v1.5.19.995).  

As far as I know I have to render the `qmd` file and upload the `html` as well as the relating `css` etc files. But it does not work: My example is the simple example from Quarto docs (https://quarto.org/docs/interactive/shiny/#hello-shiny). I clicked  "Run Document" in Rstudio and uploaded the `index.html`, `index.qmd` as well as the `index_files` to my server. 

The app does not deliver interactive parts: https://apps.katharinabrunner.de/test/

There are other Shiny apps running on that instance both native Shiny apps as well as Flexdashboards.

Related issues: 
- https://github.com/quarto-dev/quarto-cli/discussions/1997
- https://github.com/rstudio/shiny-server/issues/528

**Comment by jjallaire** [comment]
FYI you have to also upload the `.qmd` file.

**Comment by cutterkom** [comment]
> FYI you have to also upload the `.qmd` file.

I did that, I update my message.

**Comment by jcheng5** [comment]
I’m on the road today but will look at this tomorrow!

**Comment by jcheng5** [comment]
Working on this here: https://github.com/rstudio/shiny-server/pull/531

**Comment by jcheng5** [comment]
Fixed in #531. Thank you!

**Comment by cutterkom** [comment]
Thank you!
