### ISSUE TITLE
Adminstrator's Guide is Missing Hosting Model for Packaged Applications

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny-server#536]
Section 2.7 Hosting Model is missing details about how to correctly deploy applications that have been converted into packages (i.e. the Shiny code is in the `R` subdirectory). Application loading begins if R is tacked onto the end of the URL, such as, http://shiny.university.edu/applicationAsPackage/R/ (which is unsightly but otherwise there is Page Not Found Error) but it causes problems because commands like `load("datasets/experiment.RData")` no longer work like they do if `load_all()` is used at the RStudio command line from the top-level package directory to load the application. Currently, the guide looks like 
![image](https://user-images.githubusercontent.com/631218/188560495-451f84aa-a5e2-4b17-ba66-ccdc6522bb1d.png)
and it makes no mention of the kind of folder structure described in [Chapter 20 of Mastering Shiny book](https://mastering-shiny.org/scaling-packaging.html).

**Comment by jcheng5** [comment]
I think that section in the Mastering Shiny book explains it near the end, specifically: https://mastering-shiny.org/scaling-packaging.html#deploying-your-app-package
