### ISSUE TITLE
1.5.20 availability

### ISSUE THREAD

**Issue by Felixmil** [rstudio/shiny-server#539]
Hi !

During my migration to Quarto I tried to serve quarto interactive document (prerendered) on a shiny server but without success.
I could see that the PR #531 and the [1.5.20 version in NEWS](https://github.com/rstudio/shiny-server/blob/a48776b64e0fc30fc8c53ea783fe87b19c525860/NEWS#L1) should fix this.

However, I cannot find the 1.5.20 version anywhere. Am I missing something ?

Thank you for your great work.

Cheers

**Comment by andresrcs** [comment]
That is the current development version, it has not been released yet but you can clone this repo and compile it yourself to get it.

**Comment by jcheng5** [comment]
You can also install the development version of SSOS from deb/rpm via our Daily Builds website: https://dailies.rstudio.com/shiny-server/

Sorry that it's been such a delay for 1.5.20. We're stretched quite thin at the moment.

**Comment by Felixmil** [comment]
I didn't know [https://dailies.rstudio.com/shiny-server/](https://dailies.rstudio.com/shiny-server/) existed ! That will do, thank you very much.
