### ISSUE TITLE
"su: ignoring --preserve-environment" error in apps

### ISSUE THREAD

**Issue by snhansen** [rstudio/shiny-server#541]
For all sessions on all of my apps, I keep getting the following error:

```
su: ignoring --preserve-environment, it's mutually exclusive with --login
```
This doesn't seem to affect the performance of the app except that sometimes the buttons doesn't work immediately after loading the app page, but the server still writes an error log with that message.

Here's a minimal example producing this error:

```
library(shiny)

server <- function(input, output) {
  observeEvent(input$generate, {
    x <- runif(1)
    print(x)
    output$x <- renderText(x)
  })
}

ui <- fluidPage(
  actionButton("generate", label = "Generate"),
  textOutput("x")
)
```

My server config is:
```
# Instruct Shiny Server to run applications as the user "shiny"
run_as :HOME_USER:;
# preserve_logs true;

# Define a server that listens on port 3838
server {
  listen 3838;

  location / {
    user_dirs;
    members_of shinyusers;
    directory_index on;
  }
}
```

**Comment by jcheng5** [comment]
That message is totally harmless, and is emitted before the app even starts. I've been meaning to fix it but in the meantime you can safely ignore it.

The "buttons don't work immediately after loading the app page" is unrelated--does it reproduce even with as simple an app like you have here?

**Comment by snhansen** [comment]
That's good to know, thanks for the response.

As for the "buttons"-thing, I looked a little more into it. I actually mistook the button for not working while it's just that it functions with a bit of a delay if I activate the button immediately after the button is loaded. It's like a 2 second delay so it seems as if there is a bit more load time after the UI has been loaded. Subsequent actions doesn't come with this delay. I'm closing this as this is most likely intended.

**Comment by cpsyctc2** [comment]
Still happening Debian server, latest open shiny package and latest R 3.2.4
