### ISSUE TITLE
Support for multiple R versions

### ISSUE THREAD

**Issue by AshesITR** [rstudio/shiny-server#542]
When serving mutliple shiny apps from the same server, it would be nice if the R executable to be used could be specified on a per-app basis.
Currently this is only possible using the environment variable `R=/path/to/R/exe`, which takes effect for all apps hosted by the server.

Ideally, the R version to be run could be detected from the `renv.lock` file if the shiny app project makes use of `renv`.

**Comment by philibe** [comment]
Maybe this article can  be adaptable to multiple R version: 

[shiny.rstudio.com, Jeff Allen, Dec 16, 2020 :  Allowing different libraries for different apps on Shiny Server, Shiny Server Pro, and RStudio Connect](https://shiny.rstudio.com/articles/libraries.html)

**Comment by AshesITR** [comment]
This is a Pro only feature: https://docs.posit.co/shiny-server/#r_path
