### ISSUE TITLE
After updating tidyverse, the fonts on the graphics of shiny server do not appear

### ISSUE THREAD

**Issue by chuxinyuan** [rstudio/shiny-server#568]
During the update process, the following packages are installed as prompted：

libharfbuzz-dev libfribidi-dev  # for textshaping package 
libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev  # for ragg package

The result is that the fonts on the graphics on the shiny app are missing, look here: <https://shiny.cxy.cc/>

System info

Shiny Server v1.5.19.995
Node.js v16.14.0

```
R version 4.2.2 Patched (2022-11-10 r83330)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.1 LTS, RStudio 2022.7.1.554

Locale:
  LC_CTYPE=zh_CN.UTF-8       LC_NUMERIC=C               LC_TIME=zh_CN.UTF-8       
  LC_COLLATE=zh_CN.UTF-8     LC_MONETARY=zh_CN.UTF-8    LC_MESSAGES=zh_CN.UTF-8   
  LC_PAPER=zh_CN.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
  LC_TELEPHONE=C             LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C       

Package version:
  cli_3.6.1         compiler_4.2.2    cpp11_0.4.2       glue_1.6.2        graphics_4.2.2   
  grDevices_4.2.2   lifecycle_1.0.3   methods_4.2.2     rlang_1.1.1       rstudioapi_0.14  
  stats_4.2.2       systemfonts_1.1.0 textshaping_0.4.0 tools_4.2.2       utils_4.2.2      
  xfun_0.44
```

**Comment by jcheng5** [comment]
I just visited that link and it looks OK... did something change?

**Comment by chuxinyuan** [comment]
> I just visited that link and it looks OK... did something change?

Sorry, the server system is a little stuck after I messed with it, so I replaced Ubuntu22.04 with Debian 12.5.

Current version configuration:
R 4.2.2
RStudio Server 2022.07.1-554-amd64
Shiny Server 1.5.19.995-amd64

Dare not update the system, once R updated to 4.4.0 version will have problems.

**Comment by chuxinyuan** [comment]
I remember some graphics engine update after 4.2.2 and am not sure if this is the cause.
