### ISSUE TITLE
How to choose the python path for Shiny-Server.conf

### ISSUE THREAD

**Issue by Linhkust** [rstudio/shiny-server#576]
Hello, i am configuring shiny-server.conf for deploying my app on web.

Following the instructions:

> Configure Python
> 
> Next, you need to tell Shiny Server how to find Python. You can point Shiny Server at either a Python binary (e.g. /usr/bin/python3) or an absolute path to a virtualenv (e.g. /srv/shiny-server/python39-venv). You can also provide a relative path to a virtualenv (e.g. .venv) in which case, SSOS will look for that directory relative to app.py. (Don’t forget that you need to [pip install shiny](https://shiny.posit.co/py/docs/install.html) and any other Python packages needed by your app(s), into whichever Python installation or virtualenv(s) you intend to use.)
> 
> Edit the file /etc/shiny-server/shiny-server.conf (root privileges are required). Add a line with python <path-to-python-or-venv>; to the top of the file, leaving the rest of the file alone (at least for now). For example, if you wanted to use /usr/bin/python3, the end result might look like this:

```
# Use system python3 to run Shiny apps
python /usr/bin/python3;

# Instruct Shiny Server to run applications as the user "shiny"
run_as shiny;

# Define a server that listens on port 3838
server {
  listen 3838;

  # Define a location at the base URL
  location / {

    # Host the directory of Shiny Apps stored in this directory
    site_dir /srv/shiny-server;

    # Log all Shiny output to files in this directory
    log_dir /var/log/shiny-server;

    # When a user visits the base URL rather than a particular application,
    # an index of the applications available in this directory will be shown.
    directory_index on;
  }
}
```

I installed anaconda and the path for my interpreter is `/home/user_name/anaconda3/bin/python`. So i replaced
`usr/bin/python3;`
with
`/home/user_name/anaconda3/bin/python`.

But the web app cannot be opened with the log showing:
`/home/lin/anaconda3/bin/python: permission denied`

How can I fix this issue? Looking forward to your help!

**Comment by jcheng5** [comment]
The Python path you provide will be invoked by the `run_as` user. So in this case, the user `shiny` would need to be able to access `/home/lin/...`. Alternatively, you could switch to the shiny user (`sudo su - shiny`) and configure Anaconda under `/home/shiny/anaconda3/bin/python`, and use that path instead.
