### ISSUE TITLE
Sock proxy

### ISSUE THREAD

**Issue by detule** [rstudio/shiny-server#70]
Hi folks,

Was not sure what's the best place to submit this - please move where appropriate.

I have a question and wonder if you have come across this.

Hypothetically an app exceeds its specified init timeout (App is somehow ill-designed and [R] process is stuck spinning away).

Looks like the scheduler will give up trying to get a handle on the worker, and the user will get a nice 

"...application took too long to respond...."

In the process the sock server will sever the connection, but having never obtained a handle on the worker, it won't try and release it.  Consequently the worker is orphaned.

Am I missing something in the process flow?

Thanks

**Comment by jcheng5** [comment]
Going through old issues... thanks for the report and fix, this was fixed incidentally through a major refactor a few years ago.
