### ISSUE TITLE
Unable to install on CentOS 7

### ISSUE THREAD

**Issue by pshevtsov** [rstudio/shiny-server#87]
```sh
$ cat /etc/redhat-release 
CentOS Linux release 7.0.1406 (Core)

$ sudo yum install --nogpgcheck shiny-server-1.2.2.367-x86_64.rpm
…
Error: Package: shiny-server-1.2.2.367-1.x86_64 (/shiny-server-1.2.2.367-x86_64)
           Requires: libffi.so.5()(64bit)
Error: Package: shiny-server-1.2.2.367-1.x86_64 (/shiny-server-1.2.2.367-x86_64)
           Requires: libgmp.so.3()(64bit)
```

**Comment by jogan999** [comment]
Any update on this installation  please ??
However 
With the help of my Sys Admin we have installed from source. 
I can start the shiny server as user root and access the web page.
When I have tried to run application I struck with  the following error;
[INFO] shiny-server - ^[[39mError getting worker: Error: Connection attempt was aborted.
Any help resolving this will be appreciated 

Regards
Joga

**Comment by pshevtsov** [comment]
As a temporary workaround there is a way to run shiny-server on CentOS 7 via [Docker](http://docker.io/) using this [docker image](https://github.com/pshevtsov/shiny-server-docker)

**Comment by jogan999** [comment]
Thanks..
Finally I made it to work .  I have modified  configfile and made to start running server as user shiny.
I have provided read and write permissions to  the relevant folders to user account shiny.
Magic !!, it works. Thanks for your help.

Kind regards
Joga

**Comment by trestletech** [comment]
All, thanks for your patience. We just released Shiny Server 1.3.0, which is CentOS7-compatible. Please take it for a spin and let us know if you have any trouble.

http://www.rstudio.com/products/shiny/download-server/

(Bear with us as we get the rest of the documentation up to the proper version this afternoon.)

**Comment by profMikeBroyles** [comment]
tresletech - just use the install instructions even though the naming of the RPM looks to be for EL 5?

**Comment by tk3369** [comment]
doesn't work on Amazon Linux.... Is there a solution yet?

/opt/shiny-server/ext/pandoc/pandoc: error while loading shared libraries: libgmp.so.3: cannot open shared object file: No such file or directory
Error in system(paste(shQuote(pandoc_path), "--version"), intern = TRUE) : 
  error in running command

Execution halted
Warning message:
In rm(list = as.character(handle), pos = .wsconns) :
  object '52966704' not found

**Comment by jjallaire** [comment]
@trestletech It looks like we're attempting to use the RPM pandoc on Amazon Linux (I can see this from the fact that it's loading a shared library). If you use the DEB pandoc (which has no shared libraries and works on every Linux we've ever seen saved for RHEL5 then it should be okay).

**Comment by irenge** [comment]
We should switch from centos then ! which OS is the most supported ?
