### ISSUE TITLE
"Next Steps" documentation incorrect on website

### ISSUE THREAD

**Issue by mmuurr** [rstudio/shiny-server#94]
On page:
http://www.rstudio.com/products/shiny/download-server/

Tab "Ubuntu 12.04 of later" works as expected (though there is a typo on the tab... "of" instead of "or").

Tab "RadHat/CentOS", the link at the bottom in the "Next Steps" section is incorrect and is for RStudio-Server, rather than Shiny-Server.

**Comment by trestletech** [comment]
Thanks for pointing this out! Just fixed it.
