### ISSUE TITLE
shiny-server on AWS EC2 - websocker handshake error

### ISSUE THREAD

**Issue by schmidb** [rstudio/shiny-server#96]
Hi,

I am running shiny-server on AWS EC2.
Everything works fine. But there is a strange WebSocket handshake error in the JavaScript console:

WebSocket connection to 'ws://ec2-54-154-238-202.eu-west-1.compute.amazonaws.com/shinyExample/__sockjs__/276/8j9qxhul/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400

shiny 0.11
Shiny Server v1.3.0.403
Node.js v0.10.21

Any ideas?

Thanks Markus

**Comment by trestletech** [comment]
We use the "SockJS" library to create a WebSocket-like connection between the browser and the server. Since WebSockets are still relatively new technology, there's a lot of networking equipment that doesn't yet support them.

So you may see this message if the browser was unable to open a WebSocket and had to fall back to another protocol. This is expected behavior and, other than a few milliseconds of extra latency per interaction, you shouldn't see any performance issues associated with it. Let us know if you find otherwise!

**Comment by ainunnajib** [comment]
Hi, I have the same situation.

Hitting the WebSocket error in Amazon EC2. For my case, it result in my DataTables "character sort as numeric" doesn't work properly. 

In local (run App from RStudio) the sort works fine, in deployment it doesn't. When I compare the two sources, the only difference are addition of these two lines on the deployed one:
<script src="__assets__/sockjs-0.3.min.js"></script>
<script src="__assets__/shiny-server.js"></script>

Is there a way to fix this?

**Comment by ainunnajib** [comment]
I think schmidb has problem not on latency but the behavior of the application changes unexpectedly:

https://support.rstudio.com/hc/communities/public/questions/202231898-flashing-ggvis-graphs-on-shiny-server

Like in my case, the character as numeric sorting suddenly doesn't work.

**Comment by yihui** [comment]
@ainunnajib Could you explain or give an example to show what you meant by "character as numeric sorting"? And could you also print out the `library(shiny); sessionInfo()` on your EC2 server?

**Comment by ainunnajib** [comment]
My DataTables app is available publicly at: http://analytics.ainunnajib.com/RAPBD/versi-Pemprov/

If you try to sort the number columns, they will sort as text rather than numbers. Interestingly this only happens on deployment, in local (run App from RStudio) the sorting works just fine.

**Comment by ainunnajib** [comment]
@yihui : here's my session info, thanks a lot in advance!

> library(shiny); sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=C                 LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_0.11.1

loaded via a namespace (and not attached):
[1] digest_0.6.8    htmltools_0.2.6 httpuv_1.3.2    mime_0.2       
[5] R6_2.0.1        Rcpp_0.11.4     RJSONIO_1.3-0   xtable_1.7-4

**Comment by yihui** [comment]
Okay, perhaps that should be called "numeric as character sorting" (instead of the other way around). I'm not sure what a number like 123.456.789 means in your table: is it a number 123456789 or a character string `"123.456.789"` in your R data frame? My guess is the latter case, i.e. you explicitly converted the number 123456789 to a character string (via `format()` or something else). In that case, sorting will be performed on the character strings, which is locale-dependent. I see your `LC_CTYPE` is `C` on the EC2 server, and you can print out `sessionInfo()` in your local R session to see if it is different (I guess it is `en_US.UTF-8`). To make sorting characters consistent, you need to make sure the locale remains the same, e.g. you can explicitly set `Sys.setlocale('LC_CTYPE', 'en_US.UTF-8')` or `Sys.setlocale('LC_CTYPE', 'C')` in your R session.

**Comment by ainunnajib** [comment]
Thank you for your kind help into this small issue @yihui 

You're absolutely correct in analyzing what I had and did in/with the data frame.
Here's the complete code at: https://github.com/ainunnajib/analytics.ainunnajib.com/blob/master/RAPBD/versi-Pemprov/server.R

However, I have tried both setting the locale at local to follow server and vice versa; the behavior remains. Sorting works in local but not in server.

**Comment by yihui** [comment]
Okay, now I need to you print the following info both on the server and locally:

```r
sessionInfo()
str(options())
```

If possible, could you also `save()` the `data` object in the end of `renderDataTable()` (after you have formatted the columns), load it in a separate R session, and print out `str(data)`. I want to make sure the character columns in theory are really characters, or make sure the data object on the EC2 server is identical to the one in your local R session.

**Comment by ainunnajib** [comment]
PS: how should we set the locale? What I tried: I put Sys.setlocale() at both ui.R and server.R (at server), at local I did at RStudio R console as well.

Here's the details you mentioned:

sessionInfo() & options() at server 
(note that the locale is still C as I put the setlocale to utf-8 only at ui.R and server.R):
```
root@ip:/srv/shiny-server# R

R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Previously saved workspace restored]

During startup - Warning message:
Setting LC_CTYPE failed, using "C" 
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=C                 LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

> str(options())
List of 59
 $ add.smooth           : logi TRUE
 $ bitmapType           : chr "cairo"
 $ browser              : chr "xdg-open"
 $ browserNLdisabled    : logi FALSE
 $ CBoundsCheck         : logi FALSE
 $ check.bounds         : logi FALSE
 $ citation.bibtex.max  : num 1
 $ continue             : chr "+ "
 $ contrasts            : Named chr [1:2] "contr.treatment" "contr.poly"
  ..- attr(*, "names")= chr [1:2] "unordered" "ordered"
 $ defaultPackages      : chr [1:6] "datasets" "utils" "grDevices" "graphics" ...
 $ demo.ask             : chr "default"
 $ deparse.cutoff       : int 60
 $ device               :function (file = ifelse(onefile, "Rplots.pdf", "Rplot%03d.pdf"), width, 
    height, onefile, family, title, fonts, version, paper, encoding, bg, 
    fg, pointsize, pagecentre, colormodel, useDingbats, useKerning, fillOddEven, 
    compress)  
 $ device.ask.default   : logi FALSE
 $ digits               : int 7
 $ dvipscmd             : chr "dvips"
 $ echo                 : logi TRUE
 $ editor               : chr "vi"
 $ encoding             : chr "native.enc"
 $ example.ask          : chr "default"
 $ expressions          : int 5000
 $ help.search.types    : chr [1:3] "vignette" "demo" "help"
 $ help.try.all.packages: logi FALSE
 $ HTTPUserAgent        : chr "R (3.1.2 x86_64-pc-linux-gnu x86_64 linux-gnu)"
 $ internet.info        : num 2
 $ keep.source          : logi TRUE
 $ keep.source.pkgs     : logi FALSE
 $ locatorBell          : logi TRUE
 $ mailer               : chr "mailto"
 $ max.print            : int 99999
 $ menu.graphics        : logi TRUE
 $ na.action            : chr "na.omit"
 $ nwarnings            : int 50
 $ OutDec               : chr "."
 $ pager                : chr "/usr/lib/R/bin/pager"
 $ papersize            : chr "a4"
 $ pdfviewer            : chr "/usr/bin/xdg-open"
 $ pkgType              : chr "source"
 $ printcmd             : chr "/usr/bin/lpr"
 $ prompt               : chr "> "
 $ repos                : Named chr "@CRAN@"
  ..- attr(*, "names")= chr "CRAN"
 $ rl_word_breaks       : chr " \t\n\"\\'`><=%;,|&{()}"
 $ scipen               : num 0
 $ show.coef.Pvalues    : logi TRUE
 $ show.error.messages  : logi TRUE
 $ show.signif.stars    : logi TRUE
 $ str                  :List of 3
  ..$ strict.width: chr "no"
  ..$ digits.d    : num 3
  ..$ vec.len     : num 4
 $ str.dendrogram.last  : chr "`"
 $ stringsAsFactors     : logi TRUE
 $ texi2dvi             : chr "/usr/bin/texi2dvi"
 $ timeout              : num 60
 $ ts.eps               : num 1e-05
 $ ts.S.compat          : logi FALSE
 $ unzip                : chr "/usr/bin/unzip"
 $ useFancyQuotes       : logi TRUE
 $ verbose              : logi FALSE
 $ warn                 : num 0
 $ warning.length       : int 1000
 $ width                : int 80
> 

```

sessionInfo() & options() at local 
(note that the locale is now 'C' due to previous setlocale at console, it used to be utf-8; nevertheless the sorting behavior wasn't affected):
```
R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_COLLATE failed, using "C" 
3: Setting LC_TIME failed, using "C" 
4: Setting LC_MESSAGES failed, using "C" 
5: Setting LC_MONETARY failed, using "C" 
[Workspace loaded from ~/misc/APBD DKI Jakarta full/AllAPBD/.RData]

> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.1.2

> str(options())
List of 85
 $ CBoundsCheck             : logi FALSE
 $ HTTPUserAgent            : chr "R (3.1.2 x86_64-apple-darwin13.4.0 x86_64 darwin13.4.0)"
 $ OutDec                   : chr "."
 $ add.smooth               : logi TRUE
 $ bitmapType               : chr "quartz"
 $ browser                  :function (url)  
 $ browserNLdisabled        : logi FALSE
 $ buildtools.check         :function (action)  
 $ buildtools.with          :function (code)  
 $ check.bounds             : logi FALSE
 $ chron.year.abb           : logi TRUE
 $ chron.year.expand        : chr "year.expand"
 $ citation.bibtex.max      : num 1
 $ continue                 : chr "+ "
 $ contrasts                : Named chr [1:2] "contr.treatment" "contr.poly"
  ..- attr(*, "names")= chr [1:2] "unordered" "ordered"
 $ datatable.alloccol       : language max(100L, ncol(DT) + 64L)
 $ datatable.allow.cartesian: logi FALSE
 $ datatable.auto.index     : logi TRUE
 $ datatable.dfdispatchwarn : logi TRUE
 $ datatable.fread.datatable: logi TRUE
 $ datatable.integer64      : chr "integer64"
 $ datatable.nomatch        : int NA
 $ datatable.old.bywithoutby: logi FALSE
 $ datatable.optimize       : num Inf
 $ datatable.print.nrows    : int 100
 $ datatable.print.topn     : int 5
 $ datatable.showProgress   : int 1
 $ datatable.verbose        : logi FALSE
 $ datatable.warnredundantby: logi TRUE
 $ defaultPackages          : chr [1:6] "datasets" "utils" "grDevices" "graphics" ...
 $ demo.ask                 : chr "default"
 $ deparse.cutoff           : int 60
 $ device                   : chr "RStudioGD"
 $ device.ask.default       : logi FALSE
 $ digits                   : int 7
 $ dvipscmd                 : chr "dvips"
 $ echo                     : logi TRUE
 $ editor                   : chr "vi"
 $ encoding                 : chr "native.enc"
 $ error                    : language (structure(function ()  { ...
 $ example.ask              : chr "default"
 $ expressions              : int 5000
 $ ggvis.renderer           : chr "svg"
 $ help.search.types        : chr [1:3] "vignette" "demo" "help"
 $ help.try.all.packages    : logi FALSE
 $ help_type                : chr "html"
 $ httr_oauth_cache         : logi NA
 $ httr_oob_default         : logi FALSE
 $ internet.info            : num 2
 $ keep.source              : logi TRUE
 $ keep.source.pkgs         : logi FALSE
 $ locatorBell              : logi TRUE
 $ mailer                   : chr "mailto"
 $ max.print                : int 10000
 $ menu.graphics            : logi FALSE
 $ na.action                : chr "na.omit"
 $ nwarnings                : int 50
 $ pager                    :function (files, header, title, delete.file)  
 $ papersize                : chr "a4"
 $ pdfviewer                : chr "/usr/bin/open"
 $ pkgType                  : chr "mac.binary.mavericks"
 $ printcmd                 : chr "lpr"
 $ prompt                   : chr "> "
 $ repos                    : atomic [1:1] http://cran.rstudio.com
  ..- attr(*, "RStudio")= logi TRUE
 $ restart                  :function (afterRestartCommand = "")  
 $ rl_word_breaks           : chr " \t\n\"\\'`><=%;,|&{()}"
 $ scipen                   : num 0
 $ shiny.launch.browser     :function (url)  
  ..- attr(*, "shinyViewerType")= num 3
 $ show.coef.Pvalues        : logi TRUE
 $ show.error.messages      : logi TRUE
 $ show.signif.stars        : logi TRUE
 $ str                      :List of 3
  ..$ strict.width: chr "no"
  ..$ digits.d    : num 3
  ..$ vec.len     : num 4
 $ str.dendrogram.last      : chr "`"
 $ stringsAsFactors         : logi TRUE
 $ texi2dvi                 : chr "/usr/bin/texi2dvi"
 $ timeout                  : num 60
 $ ts.S.compat              : logi FALSE
 $ ts.eps                   : num 1e-05
 $ unzip                    : chr "/usr/bin/unzip"
 $ useFancyQuotes           : logi TRUE
 $ verbose                  : logi FALSE
 $ viewer                   :function (url, height = NULL)  
 $ warn                     : num 0
 $ warning.length           : int 1000
 $ width                    : int 100
> 
```

**Comment by yihui** [comment]
As I mentioned above, `Sys.setlocale('LC_CTYPE', 'en_US.UTF-8')` is the way to change LC_CTYPE. It looks you put that in `.Rprofile`?

Have you also tried to save `data` and compare the two copies from the server and your local computer, respectively? Printing out `str(data)` can be helpful to see the differences.

**Comment by yihui** [comment]
I also noticed you had the `.RData` file, and I'd recommend you to remove it, since it may make your R session unpredictable.
